# One-shot tooling image: goose migrations.
FROM golang:1.24-alpine
WORKDIR /app
RUN apk add --no-cache git && \
    go install github.com/pressly/goose/v3/cmd/goose@v3.24.1
ENTRYPOINT []
CMD ["goose", "-version"]
