// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const cancelUserDeletion = `-- name: CancelUserDeletion :execrows
UPDATE users SET status = 'active', deletion_requested_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'deletion_pending'
`

// A sign-in during the grace period cancels the deletion.
func (q *Queries) CancelUserDeletion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelUserDeletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, password_hash, display_name, locale, timezone, email_verified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, email_verified_at, password_hash, display_name, locale, unit_system, week_start, timezone, status, deletion_requested_at, sync_seq, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           *string
	PasswordHash    *string
	DisplayName     string
	Locale          string
	Timezone        string
	EmailVerifiedAt *time.Time
}

// Users, devices, refresh tokens and Apple identities.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Locale,
		arg.Timezone,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.UnitSystem,
		&i.WeekStart,
		&i.Timezone,
		&i.Status,
		&i.DeletionRequestedAt,
		&i.SyncSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppleIdentity = `-- name: GetAppleIdentity :one
SELECT user_id, apple_sub, is_private_email, linked_at FROM apple_identities WHERE apple_sub = $1
`

func (q *Queries) GetAppleIdentity(ctx context.Context, appleSub string) (AppleIdentity, error) {
	row := q.db.QueryRow(ctx, getAppleIdentity, appleSub)
	var i AppleIdentity
	err := row.Scan(
		&i.UserID,
		&i.AppleSub,
		&i.IsPrivateEmail,
		&i.LinkedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, family_id, token_hash, device_id, issued_at, expires_at, used_at, revoked_at, revoked_reason, replaced_by, user_agent, ip FROM refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

// Locks the row: two concurrent refreshes with the same token must not both
// succeed.
func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.DeviceID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, password_hash, display_name, locale, unit_system, week_start, timezone, status, deletion_requested_at, sync_seq, created_at, updated_at, deleted_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.UnitSystem,
		&i.WeekStart,
		&i.Timezone,
		&i.Status,
		&i.DeletionRequestedAt,
		&i.SyncSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, password_hash, display_name, locale, unit_system, week_start, timezone, status, deletion_requested_at, sync_seq, created_at, updated_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.UnitSystem,
		&i.WeekStart,
		&i.Timezone,
		&i.Status,
		&i.DeletionRequestedAt,
		&i.SyncSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAppleIdentity = `-- name: InsertAppleIdentity :exec
INSERT INTO apple_identities (user_id, apple_sub, is_private_email)
VALUES ($1, $2, $3)
`

type InsertAppleIdentityParams struct {
	UserID         uuid.UUID
	AppleSub       string
	IsPrivateEmail bool
}

func (q *Queries) InsertAppleIdentity(ctx context.Context, arg InsertAppleIdentityParams) error {
	_, err := q.db.Exec(ctx, insertAppleIdentity, arg.UserID, arg.AppleSub, arg.IsPrivateEmail)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, family_id, token_hash, device_id, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	DeviceID  *uuid.UUID
	ExpiresAt time.Time
	UserAgent *string
	Ip        *netip.Addr
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.DeviceID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens
SET used_at = now(), revoked_at = now(), revoked_reason = 'rotated', replaced_by = $1
WHERE id = $2
`

type MarkRefreshTokenRotatedParams struct {
	ReplacedBy *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, arg.ReplacedBy, arg.ID)
	return err
}

const reapUser = `-- name: ReapUser :execrows
DELETE FROM users
WHERE id = $1 AND status = 'deletion_pending' AND deletion_requested_at < $2
`

type ReapUserParams struct {
	ID     uuid.UUID
	Cutoff *time.Time
}

func (q *Queries) ReapUser(ctx context.Context, arg ReapUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, reapUser, arg.ID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestUserDeletion = `-- name: RequestUserDeletion :one
UPDATE users SET
    status = 'deletion_pending',
    deletion_requested_at = COALESCE(deletion_requested_at, now()),
    updated_at = now()
WHERE id = $1 AND status IN ('active', 'deletion_pending')
RETURNING id, email, email_verified_at, password_hash, display_name, locale, unit_system, week_start, timezone, status, deletion_requested_at, sync_seq, created_at, updated_at, deleted_at
`

func (q *Queries) RequestUserDeletion(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, requestUserDeletion, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.UnitSystem,
		&i.WeekStart,
		&i.Timezone,
		&i.Status,
		&i.DeletionRequestedAt,
		&i.SyncSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :execrows
UPDATE refresh_tokens SET revoked_at = now(), revoked_reason = $1
WHERE family_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshFamilyParams struct {
	Reason   *string
	FamilyID uuid.UUID
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshFamily, arg.Reason, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :execrows
UPDATE refresh_tokens SET revoked_at = now(), revoked_reason = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeUserRefreshTokensParams struct {
	Reason *string
	UserID uuid.UUID
}

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, arg RevokeUserRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRefreshTokens, arg.Reason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserEmail = `-- name: SetUserEmail :exec
UPDATE users SET email = $1, email_verified_at = $2, updated_at = now()
WHERE id = $3 AND email IS NULL
`

type SetUserEmailParams struct {
	Email           *string
	EmailVerifiedAt *time.Time
	ID              uuid.UUID
}

func (q *Queries) SetUserEmail(ctx context.Context, arg SetUserEmailParams) error {
	_, err := q.db.Exec(ctx, setUserEmail, arg.Email, arg.EmailVerifiedAt, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name = COALESCE($1, display_name),
    locale       = COALESCE($2, locale),
    unit_system  = COALESCE($3, unit_system),
    week_start   = COALESCE($4, week_start),
    timezone     = COALESCE($5, timezone),
    updated_at   = now()
WHERE id = $6
RETURNING id, email, email_verified_at, password_hash, display_name, locale, unit_system, week_start, timezone, status, deletion_requested_at, sync_seq, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	DisplayName *string
	Locale      *string
	UnitSystem  *string
	WeekStart   *int16
	Timezone    *string
	ID          uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Locale,
		arg.UnitSystem,
		arg.WeekStart,
		arg.Timezone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.UnitSystem,
		&i.WeekStart,
		&i.Timezone,
		&i.Status,
		&i.DeletionRequestedAt,
		&i.SyncSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (id, user_id, platform, model, os_version, app_version, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE SET
    platform = EXCLUDED.platform, model = EXCLUDED.model,
    os_version = EXCLUDED.os_version, app_version = EXCLUDED.app_version,
    last_seen_at = now()
WHERE devices.user_id = EXCLUDED.user_id
RETURNING id
`

type UpsertDeviceParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Platform   string
	Model      *string
	OsVersion  *string
	AppVersion *string
}

// A device id is claimed by the first account that signs in with it and is
// never re-owned: the row returns nothing if another account holds the id.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.Model,
		arg.OsVersion,
		arg.AppVersion,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const usersDueForReaping = `-- name: UsersDueForReaping :many
SELECT id FROM users
WHERE status = 'deletion_pending' AND deletion_requested_at < $1
ORDER BY deletion_requested_at
`

// Hard deletion after the grace period. Everything the user owns goes with
// the row through ON DELETE CASCADE.
func (q *Queries) UsersDueForReaping(ctx context.Context, cutoff *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, usersDueForReaping, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
