// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalogue.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const exerciseStatuses = `-- name: ExerciseStatuses :many
SELECT id, status FROM exercises WHERE id = ANY($1::uuid[])
`

type ExerciseStatusesRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) ExerciseStatuses(ctx context.Context, ids []uuid.UUID) ([]ExerciseStatusesRow, error) {
	rows, err := q.db.Query(ctx, exerciseStatuses, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseStatusesRow{}
	for rows.Next() {
		var i ExerciseStatusesRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseBySlug = `-- name: GetExerciseBySlug :one
SELECT e.id, e.slug, e.name, e.aka, e.family_id, e.default_measure, e.load_semantics, e.is_bodyweight, e.unilateral, e.tempo_applicable, e.equipment, e.summary, e.cues, e.common_faults, e.status, e.content_version_id, e.created_at, e.updated_at, f.slug AS family_slug
FROM exercises e
JOIN families f ON f.id = e.family_id
WHERE e.slug = $1 AND e.status <> 'retired'
`

type GetExerciseBySlugRow struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Aka              []string
	FamilyID         uuid.UUID
	DefaultMeasure   string
	LoadSemantics    string
	IsBodyweight     bool
	Unilateral       bool
	TempoApplicable  bool
	Equipment        []string
	Summary          string
	Cues             []string
	CommonFaults     []string
	Status           string
	ContentVersionID uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	FamilySlug       string
}

func (q *Queries) GetExerciseBySlug(ctx context.Context, slug string) (GetExerciseBySlugRow, error) {
	row := q.db.QueryRow(ctx, getExerciseBySlug, slug)
	var i GetExerciseBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Aka,
		&i.FamilyID,
		&i.DefaultMeasure,
		&i.LoadSemantics,
		&i.IsBodyweight,
		&i.Unilateral,
		&i.TempoApplicable,
		&i.Equipment,
		&i.Summary,
		&i.Cues,
		&i.CommonFaults,
		&i.Status,
		&i.ContentVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FamilySlug,
	)
	return i, err
}

const insertUserBand = `-- name: InsertUserBand :one
INSERT INTO bands (id, owner_user_id, brand, colour_label, resistance_min_kg, resistance_max_kg, length_cm, thickness_mm)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_user_id, brand, colour_label, resistance_min_kg, resistance_max_kg, length_cm, thickness_mm, created_at, updated_at, deleted_at
`

type InsertUserBandParams struct {
	ID              uuid.UUID
	OwnerUserID     *uuid.UUID
	Brand           string
	ColourLabel     string
	ResistanceMinKg pgtype.Numeric
	ResistanceMaxKg pgtype.Numeric
	LengthCm        pgtype.Numeric
	ThicknessMm     pgtype.Numeric
}

func (q *Queries) InsertUserBand(ctx context.Context, arg InsertUserBandParams) (Band, error) {
	row := q.db.QueryRow(ctx, insertUserBand,
		arg.ID,
		arg.OwnerUserID,
		arg.Brand,
		arg.ColourLabel,
		arg.ResistanceMinKg,
		arg.ResistanceMaxKg,
		arg.LengthCm,
		arg.ThicknessMm,
	)
	var i Band
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Brand,
		&i.ColourLabel,
		&i.ResistanceMinKg,
		&i.ResistanceMaxKg,
		&i.LengthCm,
		&i.ThicknessMm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBandsForUser = `-- name: ListBandsForUser :many
SELECT id, owner_user_id, brand, colour_label, resistance_min_kg, resistance_max_kg, length_cm, thickness_mm, created_at, updated_at, deleted_at FROM bands
WHERE deleted_at IS NULL AND (owner_user_id IS NULL OR owner_user_id = $1)
ORDER BY brand, colour_label, id
`

func (q *Queries) ListBandsForUser(ctx context.Context, ownerUserID *uuid.UUID) ([]Band, error) {
	rows, err := q.db.Query(ctx, listBandsForUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Band{}
	for rows.Next() {
		var i Band
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Brand,
			&i.ColourLabel,
			&i.ResistanceMinKg,
			&i.ResistanceMaxKg,
			&i.LengthCm,
			&i.ThicknessMm,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercises = `-- name: ListExercises :many

SELECT e.id, e.slug, e.name, e.aka, e.family_id, e.default_measure, e.load_semantics, e.is_bodyweight, e.unilateral, e.tempo_applicable, e.equipment, e.summary, e.cues, e.common_faults, e.status, e.content_version_id, e.created_at, e.updated_at, f.slug AS family_slug
FROM exercises e
JOIN families f ON f.id = e.family_id
WHERE e.status <> 'retired'
  AND ($1::text IS NULL OR f.slug = $1)
  AND ($2::text IS NULL OR $2::text = ANY(e.equipment))
  AND ($3::text IS NULL
       OR e.name ILIKE '%' || $3 || '%'
       OR e.name % $3
       OR EXISTS (SELECT 1 FROM unnest(e.aka) a WHERE a ILIKE '%' || $3 || '%'))
ORDER BY
  CASE WHEN $3::text IS NULL THEN 0 ELSE similarity(e.name, $3) END DESC,
  e.name, e.slug
`

type ListExercisesParams struct {
	Family    *string
	Equipment *string
	Q         *string
}

type ListExercisesRow struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Aka              []string
	FamilyID         uuid.UUID
	DefaultMeasure   string
	LoadSemantics    string
	IsBodyweight     bool
	Unilateral       bool
	TempoApplicable  bool
	Equipment        []string
	Summary          string
	Cues             []string
	CommonFaults     []string
	Status           string
	ContentVersionID uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	FamilySlug       string
}

// Exercises and bands as the API reads them.
func (q *Queries) ListExercises(ctx context.Context, arg ListExercisesParams) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises, arg.Family, arg.Equipment, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExercisesRow{}
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Aka,
			&i.FamilyID,
			&i.DefaultMeasure,
			&i.LoadSemantics,
			&i.IsBodyweight,
			&i.Unilateral,
			&i.TempoApplicable,
			&i.Equipment,
			&i.Summary,
			&i.Cues,
			&i.CommonFaults,
			&i.Status,
			&i.ContentVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FamilySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUserBand = `-- name: SoftDeleteUserBand :execrows
UPDATE bands SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND owner_user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserBandParams struct {
	ID          uuid.UUID
	OwnerUserID *uuid.UUID
}

func (q *Queries) SoftDeleteUserBand(ctx context.Context, arg SoftDeleteUserBandParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUserBand, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const visibleBandIDs = `-- name: VisibleBandIDs :many
SELECT id FROM bands
WHERE id = ANY($1::uuid[]) AND (owner_user_id IS NULL OR owner_user_id = $2)
`

type VisibleBandIDsParams struct {
	Ids    []uuid.UUID
	UserID *uuid.UUID
}

// Bands a user may log with: the catalogue and their own, deleted or not,
// so repeating an old set keeps working after a band is retired.
func (q *Queries) VisibleBandIDs(ctx context.Context, arg VisibleBandIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, visibleBandIDs, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
