// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: content.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllSkillEdges = `-- name: DeleteAllSkillEdges :exec
DELETE FROM skill_edges
`

func (q *Queries) DeleteAllSkillEdges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllSkillEdges)
	return err
}

const deleteInjuryPrehab = `-- name: DeleteInjuryPrehab :exec
DELETE FROM injury_prehab_exercises WHERE risk_id = $1
`

func (q *Queries) DeleteInjuryPrehab(ctx context.Context, riskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInjuryPrehab, riskID)
	return err
}

const deleteInjuryRisksNotIn = `-- name: DeleteInjuryRisksNotIn :exec
DELETE FROM skill_injury_risks
WHERE skill_id = $1 AND NOT (id = ANY($2::uuid[]))
`

type DeleteInjuryRisksNotInParams struct {
	SkillID uuid.UUID
	Keep    []uuid.UUID
}

// Injury content references no user rows, so entries gone from a skill file
// are deleted outright.
func (q *Queries) DeleteInjuryRisksNotIn(ctx context.Context, arg DeleteInjuryRisksNotInParams) error {
	_, err := q.db.Exec(ctx, deleteInjuryRisksNotIn, arg.SkillID, arg.Keep)
	return err
}

const deleteSkillLevelExercises = `-- name: DeleteSkillLevelExercises :exec

DELETE FROM skill_level_exercises WHERE skill_level_id = $1
`

// Associations carry no user data, so they are replaced wholesale.
func (q *Queries) DeleteSkillLevelExercises(ctx context.Context, skillLevelID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillLevelExercises, skillLevelID)
	return err
}

const findPrerequisiteCycles = `-- name: FindPrerequisiteCycles :many
WITH RECURSIVE walk (origin, node, path, cyclic) AS (
    SELECT e.from_skill_level_id, e.to_skill_level_id,
           ARRAY[e.from_skill_level_id, e.to_skill_level_id],
           e.from_skill_level_id = e.to_skill_level_id
    FROM skill_edges e
    WHERE e.relation = 'prerequisite'
  UNION ALL
    SELECT w.origin, e.to_skill_level_id,
           w.path || e.to_skill_level_id,
           e.to_skill_level_id = ANY(w.path)
    FROM walk w
    JOIN skill_edges e ON e.from_skill_level_id = w.node AND e.relation = 'prerequisite'
    WHERE NOT w.cyclic
)
SELECT DISTINCT origin::uuid AS skill_level_id FROM walk WHERE cyclic AND node = origin
`

// Belt and braces for deviation D-7: contentlint already rejected cycles, but
// the seed re-checks the graph as the database now holds it. Returns the ids
// of levels that can reach themselves through prerequisite edges.
func (q *Queries) FindPrerequisiteCycles(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findPrerequisiteCycles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var skill_level_id uuid.UUID
		if err := rows.Scan(&skill_level_id); err != nil {
			return nil, err
		}
		items = append(items, skill_level_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestContentVersion = `-- name: GetLatestContentVersion :one

SELECT id, checksum, git_sha, item_counts, applied_at, applied_by
FROM content_versions
ORDER BY applied_at DESC, id DESC
LIMIT 1
`

// Content import (cmd/seed). Every upsert is keyed on slug and leaves a row
// untouched — updated_at and content_version_id included — when nothing in it
// changed. The CTE returns the id whether the row was inserted, updated or
// left alone: the INSERT returns nothing when its WHERE suppresses the update,
// and the plain SELECT sees the pre-statement snapshot, so exactly one side
// yields the id.
// The newest version is what the database currently holds; its checksum is
// the /v1/skills ETag.
func (q *Queries) GetLatestContentVersion(ctx context.Context) (ContentVersion, error) {
	row := q.db.QueryRow(ctx, getLatestContentVersion)
	var i ContentVersion
	err := row.Scan(
		&i.ID,
		&i.Checksum,
		&i.GitSha,
		&i.ItemCounts,
		&i.AppliedAt,
		&i.AppliedBy,
	)
	return i, err
}

const insertContentVersion = `-- name: InsertContentVersion :exec
INSERT INTO content_versions (id, checksum, git_sha, item_counts, applied_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertContentVersionParams struct {
	ID         uuid.UUID
	Checksum   []byte
	GitSha     *string
	ItemCounts []byte
	AppliedBy  *string
}

func (q *Queries) InsertContentVersion(ctx context.Context, arg InsertContentVersionParams) error {
	_, err := q.db.Exec(ctx, insertContentVersion,
		arg.ID,
		arg.Checksum,
		arg.GitSha,
		arg.ItemCounts,
		arg.AppliedBy,
	)
	return err
}

const insertInjuryPrehab = `-- name: InsertInjuryPrehab :exec
INSERT INTO injury_prehab_exercises (risk_id, exercise_id, order_index)
VALUES ($1, $2, $3)
`

type InsertInjuryPrehabParams struct {
	RiskID     uuid.UUID
	ExerciseID uuid.UUID
	OrderIndex int16
}

func (q *Queries) InsertInjuryPrehab(ctx context.Context, arg InsertInjuryPrehabParams) error {
	_, err := q.db.Exec(ctx, insertInjuryPrehab, arg.RiskID, arg.ExerciseID, arg.OrderIndex)
	return err
}

const insertSkillEdge = `-- name: InsertSkillEdge :exec
INSERT INTO skill_edges (from_skill_level_id, to_skill_level_id, relation, weight)
VALUES ($1, $2, $3, $4)
`

type InsertSkillEdgeParams struct {
	FromSkillLevelID uuid.UUID
	ToSkillLevelID   uuid.UUID
	Relation         string
	Weight           pgtype.Numeric
}

func (q *Queries) InsertSkillEdge(ctx context.Context, arg InsertSkillEdgeParams) error {
	_, err := q.db.Exec(ctx, insertSkillEdge,
		arg.FromSkillLevelID,
		arg.ToSkillLevelID,
		arg.Relation,
		arg.Weight,
	)
	return err
}

const insertSkillLevelExercise = `-- name: InsertSkillLevelExercise :exec
INSERT INTO skill_level_exercises (skill_level_id, exercise_id, role, order_index)
VALUES ($1, $2, $3, $4)
`

type InsertSkillLevelExerciseParams struct {
	SkillLevelID uuid.UUID
	ExerciseID   uuid.UUID
	Role         string
	OrderIndex   int16
}

func (q *Queries) InsertSkillLevelExercise(ctx context.Context, arg InsertSkillLevelExerciseParams) error {
	_, err := q.db.Exec(ctx, insertSkillLevelExercise,
		arg.SkillLevelID,
		arg.ExerciseID,
		arg.Role,
		arg.OrderIndex,
	)
	return err
}

const listSkillLevelSlugs = `-- name: ListSkillLevelSlugs :many
SELECT slug FROM skill_levels WHERE skill_id = $1 ORDER BY order_index
`

func (q *Queries) ListSkillLevelSlugs(ctx context.Context, skillID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSkillLevelSlugs, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireExercisesNotIn = `-- name: RetireExercisesNotIn :execrows
UPDATE exercises
SET status = 'retired', content_version_id = $1, updated_at = now()
WHERE status <> 'retired' AND NOT (slug = ANY($2::text[]))
`

type RetireExercisesNotInParams struct {
	ContentVersionID uuid.UUID
	Slugs            []string
}

// Removal is soft: rows gone from content are retired, never deleted,
// because logged set elements reference them.
func (q *Queries) RetireExercisesNotIn(ctx context.Context, arg RetireExercisesNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireExercisesNotIn, arg.ContentVersionID, arg.Slugs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireSkillsNotIn = `-- name: RetireSkillsNotIn :execrows
UPDATE skills
SET status = 'retired', content_version_id = $1, updated_at = now()
WHERE status <> 'retired' AND NOT (slug = ANY($2::text[]))
`

type RetireSkillsNotInParams struct {
	ContentVersionID uuid.UUID
	Slugs            []string
}

func (q *Queries) RetireSkillsNotIn(ctx context.Context, arg RetireSkillsNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireSkillsNotIn, arg.ContentVersionID, arg.Slugs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteGlobalBandsNotIn = `-- name: SoftDeleteGlobalBandsNotIn :execrows
UPDATE bands
SET deleted_at = now(), updated_at = now()
WHERE owner_user_id IS NULL AND deleted_at IS NULL
  AND NOT ((brand || E'\x1f' || colour_label) = ANY($1::text[]))
`

// Global bands gone from content are soft-deleted; logged assistance keeps
// pointing at them.
func (q *Queries) SoftDeleteGlobalBandsNotIn(ctx context.Context, keys []string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteGlobalBandsNotIn, keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertExercise = `-- name: UpsertExercise :one
WITH up AS (
    INSERT INTO exercises AS e (
        id, slug, name, aka, family_id, default_measure, load_semantics,
        is_bodyweight, unilateral, tempo_applicable, equipment, summary, cues,
        common_faults, status, content_version_id
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13,
        $14, $15, $16
    )
    ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name, aka = EXCLUDED.aka, family_id = EXCLUDED.family_id,
        default_measure = EXCLUDED.default_measure, load_semantics = EXCLUDED.load_semantics,
        is_bodyweight = EXCLUDED.is_bodyweight, unilateral = EXCLUDED.unilateral,
        tempo_applicable = EXCLUDED.tempo_applicable, equipment = EXCLUDED.equipment,
        summary = EXCLUDED.summary, cues = EXCLUDED.cues, common_faults = EXCLUDED.common_faults,
        status = EXCLUDED.status, content_version_id = EXCLUDED.content_version_id,
        updated_at = now()
    WHERE (e.name, e.aka, e.family_id, e.default_measure, e.load_semantics, e.is_bodyweight,
           e.unilateral, e.tempo_applicable, e.equipment, e.summary, e.cues, e.common_faults, e.status)
      IS DISTINCT FROM
          (EXCLUDED.name, EXCLUDED.aka, EXCLUDED.family_id, EXCLUDED.default_measure,
           EXCLUDED.load_semantics, EXCLUDED.is_bodyweight, EXCLUDED.unilateral,
           EXCLUDED.tempo_applicable, EXCLUDED.equipment, EXCLUDED.summary, EXCLUDED.cues,
           EXCLUDED.common_faults, EXCLUDED.status)
    RETURNING e.id
)
SELECT up.id FROM up
UNION ALL
SELECT exercises.id FROM exercises WHERE exercises.slug = $2
LIMIT 1
`

type UpsertExerciseParams struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Aka              []string
	FamilyID         uuid.UUID
	DefaultMeasure   string
	LoadSemantics    string
	IsBodyweight     bool
	Unilateral       bool
	TempoApplicable  bool
	Equipment        []string
	Summary          string
	Cues             []string
	CommonFaults     []string
	Status           string
	ContentVersionID uuid.UUID
}

func (q *Queries) UpsertExercise(ctx context.Context, arg UpsertExerciseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertExercise,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Aka,
		arg.FamilyID,
		arg.DefaultMeasure,
		arg.LoadSemantics,
		arg.IsBodyweight,
		arg.Unilateral,
		arg.TempoApplicable,
		arg.Equipment,
		arg.Summary,
		arg.Cues,
		arg.CommonFaults,
		arg.Status,
		arg.ContentVersionID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertFamily = `-- name: UpsertFamily :one
WITH up AS (
    INSERT INTO families AS f (id, slug, name, order_index)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (slug) DO UPDATE
        SET name = EXCLUDED.name, order_index = EXCLUDED.order_index
        WHERE (f.name, f.order_index) IS DISTINCT FROM (EXCLUDED.name, EXCLUDED.order_index)
    RETURNING f.id
)
SELECT up.id FROM up
UNION ALL
SELECT families.id FROM families WHERE families.slug = $2
LIMIT 1
`

type UpsertFamilyParams struct {
	ID         uuid.UUID
	Slug       string
	Name       string
	OrderIndex int16
}

func (q *Queries) UpsertFamily(ctx context.Context, arg UpsertFamilyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertFamily,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.OrderIndex,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertGlobalBand = `-- name: UpsertGlobalBand :exec
INSERT INTO bands (id, owner_user_id, brand, colour_label, resistance_min_kg,
                   resistance_max_kg, length_cm, thickness_mm)
VALUES ($1, NULL, $2, $3, $4, $5,
        $6, $7)
ON CONFLICT (owner_user_id, brand, colour_label) WHERE deleted_at IS NULL DO UPDATE SET
    resistance_min_kg = EXCLUDED.resistance_min_kg, resistance_max_kg = EXCLUDED.resistance_max_kg,
    length_cm = EXCLUDED.length_cm, thickness_mm = EXCLUDED.thickness_mm, updated_at = now()
WHERE (bands.resistance_min_kg, bands.resistance_max_kg, bands.length_cm, bands.thickness_mm)
  IS DISTINCT FROM
      (EXCLUDED.resistance_min_kg, EXCLUDED.resistance_max_kg, EXCLUDED.length_cm, EXCLUDED.thickness_mm)
`

type UpsertGlobalBandParams struct {
	ID              uuid.UUID
	Brand           string
	ColourLabel     string
	ResistanceMinKg pgtype.Numeric
	ResistanceMaxKg pgtype.Numeric
	LengthCm        pgtype.Numeric
	ThicknessMm     pgtype.Numeric
}

func (q *Queries) UpsertGlobalBand(ctx context.Context, arg UpsertGlobalBandParams) error {
	_, err := q.db.Exec(ctx, upsertGlobalBand,
		arg.ID,
		arg.Brand,
		arg.ColourLabel,
		arg.ResistanceMinKg,
		arg.ResistanceMaxKg,
		arg.LengthCm,
		arg.ThicknessMm,
	)
	return err
}

const upsertInjuryRisk = `-- name: UpsertInjuryRisk :one
WITH up AS (
    INSERT INTO skill_injury_risks AS r (
        id, skill_id, region, name, description, risk_factors, early_signs,
        disclaimer, order_index, content_version_id
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7,
        'educational_only', $8, $9
    )
    ON CONFLICT (skill_id, region, name) DO UPDATE SET
        description = EXCLUDED.description, risk_factors = EXCLUDED.risk_factors,
        early_signs = EXCLUDED.early_signs, order_index = EXCLUDED.order_index,
        content_version_id = EXCLUDED.content_version_id
    WHERE (r.description, r.risk_factors, r.early_signs, r.order_index)
      IS DISTINCT FROM
          (EXCLUDED.description, EXCLUDED.risk_factors, EXCLUDED.early_signs, EXCLUDED.order_index)
    RETURNING r.id
)
SELECT up.id FROM up
UNION ALL
SELECT skill_injury_risks.id FROM skill_injury_risks
WHERE skill_injury_risks.skill_id = $2
  AND skill_injury_risks.region = $3 AND skill_injury_risks.name = $4
LIMIT 1
`

type UpsertInjuryRiskParams struct {
	ID               uuid.UUID
	SkillID          uuid.UUID
	Region           string
	Name             string
	Description      string
	RiskFactors      []string
	EarlySigns       []string
	OrderIndex       int16
	ContentVersionID uuid.UUID
}

func (q *Queries) UpsertInjuryRisk(ctx context.Context, arg UpsertInjuryRiskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertInjuryRisk,
		arg.ID,
		arg.SkillID,
		arg.Region,
		arg.Name,
		arg.Description,
		arg.RiskFactors,
		arg.EarlySigns,
		arg.OrderIndex,
		arg.ContentVersionID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSkill = `-- name: UpsertSkill :one
WITH up AS (
    INSERT INTO skills AS s (
        id, slug, family_id, name, aka, difficulty_tier, is_milestone, summary,
        primary_muscles, common_faults, map_constellation, map_x, map_y, status,
        content_version_id
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14,
        $15
    )
    ON CONFLICT (slug) DO UPDATE SET
        family_id = EXCLUDED.family_id, name = EXCLUDED.name, aka = EXCLUDED.aka,
        difficulty_tier = EXCLUDED.difficulty_tier, is_milestone = EXCLUDED.is_milestone,
        summary = EXCLUDED.summary, primary_muscles = EXCLUDED.primary_muscles,
        common_faults = EXCLUDED.common_faults, map_constellation = EXCLUDED.map_constellation,
        map_x = EXCLUDED.map_x, map_y = EXCLUDED.map_y, status = EXCLUDED.status,
        content_version_id = EXCLUDED.content_version_id, updated_at = now()
    WHERE (s.family_id, s.name, s.aka, s.difficulty_tier, s.is_milestone, s.summary,
           s.primary_muscles, s.common_faults, s.map_constellation, s.map_x, s.map_y, s.status)
      IS DISTINCT FROM
          (EXCLUDED.family_id, EXCLUDED.name, EXCLUDED.aka, EXCLUDED.difficulty_tier,
           EXCLUDED.is_milestone, EXCLUDED.summary, EXCLUDED.primary_muscles,
           EXCLUDED.common_faults, EXCLUDED.map_constellation, EXCLUDED.map_x, EXCLUDED.map_y,
           EXCLUDED.status)
    RETURNING s.id
)
SELECT up.id FROM up
UNION ALL
SELECT skills.id FROM skills WHERE skills.slug = $2
LIMIT 1
`

type UpsertSkillParams struct {
	ID               uuid.UUID
	Slug             string
	FamilyID         uuid.UUID
	Name             string
	Aka              []string
	DifficultyTier   int16
	IsMilestone      bool
	Summary          string
	PrimaryMuscles   []string
	CommonFaults     []string
	MapConstellation *string
	MapX             pgtype.Numeric
	MapY             pgtype.Numeric
	Status           string
	ContentVersionID uuid.UUID
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSkill,
		arg.ID,
		arg.Slug,
		arg.FamilyID,
		arg.Name,
		arg.Aka,
		arg.DifficultyTier,
		arg.IsMilestone,
		arg.Summary,
		arg.PrimaryMuscles,
		arg.CommonFaults,
		arg.MapConstellation,
		arg.MapX,
		arg.MapY,
		arg.Status,
		arg.ContentVersionID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSkillLevel = `-- name: UpsertSkillLevel :one
WITH up AS (
    INSERT INTO skill_levels AS l (
        id, skill_id, order_index, slug, name, description, unlock_criteria, est_weeks_from_prev
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8
    )
    ON CONFLICT (skill_id, slug) DO UPDATE SET
        order_index = EXCLUDED.order_index, name = EXCLUDED.name,
        description = EXCLUDED.description, unlock_criteria = EXCLUDED.unlock_criteria,
        est_weeks_from_prev = EXCLUDED.est_weeks_from_prev, updated_at = now()
    WHERE (l.order_index, l.name, l.description, l.unlock_criteria, l.est_weeks_from_prev)
      IS DISTINCT FROM
          (EXCLUDED.order_index, EXCLUDED.name, EXCLUDED.description,
           EXCLUDED.unlock_criteria, EXCLUDED.est_weeks_from_prev)
    RETURNING l.id
)
SELECT up.id FROM up
UNION ALL
SELECT skill_levels.id FROM skill_levels
WHERE skill_levels.skill_id = $2 AND skill_levels.slug = $4
LIMIT 1
`

type UpsertSkillLevelParams struct {
	ID               uuid.UUID
	SkillID          uuid.UUID
	OrderIndex       int16
	Slug             string
	Name             string
	Description      string
	UnlockCriteria   []byte
	EstWeeksFromPrev *int16
}

func (q *Queries) UpsertSkillLevel(ctx context.Context, arg UpsertSkillLevelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSkillLevel,
		arg.ID,
		arg.SkillID,
		arg.OrderIndex,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.UnlockCriteria,
		arg.EstWeeksFromPrev,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
