// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachElementMedia = `-- name: AttachElementMedia :exec
INSERT INTO set_element_media (set_element_id, user_id, media_id, order_index)
SELECT $1, $2, m.id, (m.ord - 1)::smallint
FROM unnest($3::uuid[]) WITH ORDINALITY AS m(id, ord)
ON CONFLICT (set_element_id, media_id) DO UPDATE SET order_index = EXCLUDED.order_index
`

type AttachElementMediaParams struct {
	SetElementID uuid.UUID
	UserID       uuid.UUID
	MediaIds     []uuid.UUID
}

func (q *Queries) AttachElementMedia(ctx context.Context, arg AttachElementMediaParams) error {
	_, err := q.db.Exec(ctx, attachElementMedia, arg.SetElementID, arg.UserID, arg.MediaIds)
	return err
}

const detachMedia = `-- name: DetachMedia :exec
DELETE FROM set_element_media WHERE media_id = $1 AND user_id = $2
`

type DetachMediaParams struct {
	MediaID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DetachMedia(ctx context.Context, arg DetachMediaParams) error {
	_, err := q.db.Exec(ctx, detachMedia, arg.MediaID, arg.UserID)
	return err
}

const detachOtherElementMedia = `-- name: DetachOtherElementMedia :exec
DELETE FROM set_element_media
WHERE set_element_id = $1 AND user_id = $2 AND NOT (media_id = ANY($3::uuid[]))
`

type DetachOtherElementMediaParams struct {
	SetElementID uuid.UUID
	UserID       uuid.UUID
	Keep         []uuid.UUID
}

func (q *Queries) DetachOtherElementMedia(ctx context.Context, arg DetachOtherElementMediaParams) error {
	_, err := q.db.Exec(ctx, detachOtherElementMedia, arg.SetElementID, arg.UserID, arg.Keep)
	return err
}

const expirePendingMedia = `-- name: ExpirePendingMedia :many
UPDATE media_assets SET status = 'failed'
WHERE status = 'pending' AND created_at < $1 AND deleted_at IS NULL
RETURNING storage_key
`

// Uploads never completed: their objects, if any, are removed and the asset
// marked failed.
func (q *Queries) ExpirePendingMedia(ctx context.Context, before time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, expirePendingMedia, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, owner_user_id, kind, storage_key, mime, bytes, width, height, duration_s, poster_key, checksum_sha256, status, created_at, ready_at, deleted_at FROM media_assets WHERE id = $1 AND owner_user_id = $2 AND deleted_at IS NULL
`

type GetMediaAssetParams struct {
	ID          uuid.UUID
	OwnerUserID *uuid.UUID
}

func (q *Queries) GetMediaAsset(ctx context.Context, arg GetMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, arg.ID, arg.OwnerUserID)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationS,
		&i.PosterKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertMediaAsset = `-- name: InsertMediaAsset :one

INSERT INTO media_assets (id, owner_user_id, kind, storage_key, mime, bytes, width, height)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
RETURNING id, owner_user_id, kind, storage_key, mime, bytes, width, height, duration_s, poster_key, checksum_sha256, status, created_at, ready_at, deleted_at
`

type InsertMediaAssetParams struct {
	ID          uuid.UUID
	OwnerUserID *uuid.UUID
	Kind        string
	StorageKey  string
	Mime        string
	Bytes       int64
	Width       *int32
	Height      *int32
}

// Media assets and their attachment to set elements.
func (q *Queries) InsertMediaAsset(ctx context.Context, arg InsertMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, insertMediaAsset,
		arg.ID,
		arg.OwnerUserID,
		arg.Kind,
		arg.StorageKey,
		arg.Mime,
		arg.Bytes,
		arg.Width,
		arg.Height,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationS,
		&i.PosterKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const listElementMedia = `-- name: ListElementMedia :many
SELECT sem.set_element_id, sem.media_id
FROM set_element_media sem
JOIN set_elements el ON el.id = sem.set_element_id
JOIN media_assets m ON m.id = sem.media_id
WHERE sem.user_id = $1 AND el.session_id = $2 AND m.deleted_at IS NULL
ORDER BY sem.set_element_id, sem.order_index, sem.media_id
`

type ListElementMediaParams struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
}

type ListElementMediaRow struct {
	SetElementID uuid.UUID
	MediaID      uuid.UUID
}

func (q *Queries) ListElementMedia(ctx context.Context, arg ListElementMediaParams) ([]ListElementMediaRow, error) {
	rows, err := q.db.Query(ctx, listElementMedia, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListElementMediaRow{}
	for rows.Next() {
		var i ListElementMediaRow
		if err := rows.Scan(&i.SetElementID, &i.MediaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaFailed = `-- name: MarkMediaFailed :one
UPDATE media_assets SET status = 'failed'
WHERE id = $1 AND owner_user_id = $2 AND deleted_at IS NULL AND status = 'pending'
RETURNING id, owner_user_id, kind, storage_key, mime, bytes, width, height, duration_s, poster_key, checksum_sha256, status, created_at, ready_at, deleted_at
`

type MarkMediaFailedParams struct {
	ID          uuid.UUID
	OwnerUserID *uuid.UUID
}

func (q *Queries) MarkMediaFailed(ctx context.Context, arg MarkMediaFailedParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, markMediaFailed, arg.ID, arg.OwnerUserID)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationS,
		&i.PosterKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const markMediaReady = `-- name: MarkMediaReady :one
UPDATE media_assets SET status = 'ready', ready_at = COALESCE(ready_at, now())
WHERE id = $1 AND owner_user_id = $2 AND deleted_at IS NULL AND status IN ('pending', 'ready')
RETURNING id, owner_user_id, kind, storage_key, mime, bytes, width, height, duration_s, poster_key, checksum_sha256, status, created_at, ready_at, deleted_at
`

type MarkMediaReadyParams struct {
	ID          uuid.UUID
	OwnerUserID *uuid.UUID
}

func (q *Queries) MarkMediaReady(ctx context.Context, arg MarkMediaReadyParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, markMediaReady, arg.ID, arg.OwnerUserID)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationS,
		&i.PosterKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const readyMediaIDs = `-- name: ReadyMediaIDs :many
SELECT id FROM media_assets
WHERE owner_user_id = $1 AND id = ANY($2::uuid[]) AND status = 'ready' AND deleted_at IS NULL
`

type ReadyMediaIDsParams struct {
	OwnerUserID *uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) ReadyMediaIDs(ctx context.Context, arg ReadyMediaIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, readyMediaIDs, arg.OwnerUserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMediaAsset = `-- name: SoftDeleteMediaAsset :one
UPDATE media_assets SET deleted_at = now()
WHERE id = $1 AND owner_user_id = $2 AND deleted_at IS NULL
RETURNING id, owner_user_id, kind, storage_key, mime, bytes, width, height, duration_s, poster_key, checksum_sha256, status, created_at, ready_at, deleted_at
`

type SoftDeleteMediaAssetParams struct {
	ID          uuid.UUID
	OwnerUserID *uuid.UUID
}

func (q *Queries) SoftDeleteMediaAsset(ctx context.Context, arg SoftDeleteMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, softDeleteMediaAsset, arg.ID, arg.OwnerUserID)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.StorageKey,
		&i.Mime,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.DurationS,
		&i.PosterKey,
		&i.ChecksumSha256,
		&i.Status,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.DeletedAt,
	)
	return i, err
}

const touchElementsWithMedia = `-- name: TouchElementsWithMedia :exec
UPDATE set_elements el SET server_updated_at = now()
FROM set_element_media sem
WHERE sem.media_id = $1 AND sem.user_id = $2 AND el.id = sem.set_element_id
`

type TouchElementsWithMediaParams struct {
	MediaID uuid.UUID
	UserID  uuid.UUID
}

// Touches the elements an asset is attached to, so the detachment syncs.
func (q *Queries) TouchElementsWithMedia(ctx context.Context, arg TouchElementsWithMediaParams) error {
	_, err := q.db.Exec(ctx, touchElementsWithMedia, arg.MediaID, arg.UserID)
	return err
}
