// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppleIdentity struct {
	UserID         uuid.UUID
	AppleSub       string
	IsPrivateEmail bool
	LinkedAt       time.Time
}

type Badge struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Description      string
	Tier             int16
	Criteria         []byte
	ContentVersionID uuid.UUID
}

type Band struct {
	ID              uuid.UUID
	OwnerUserID     *uuid.UUID
	Brand           string
	ColourLabel     string
	ResistanceMinKg pgtype.Numeric
	ResistanceMaxKg pgtype.Numeric
	LengthCm        pgtype.Numeric
	ThicknessMm     pgtype.Numeric
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type ContentVersion struct {
	ID         uuid.UUID
	Checksum   []byte
	GitSha     *string
	ItemCounts []byte
	AppliedAt  time.Time
	AppliedBy  *string
}

type Device struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Platform    string
	Model       *string
	OsVersion   *string
	AppVersion  *string
	PushToken   *string
	LastSyncSeq int64
	LastSeenAt  time.Time
	CreatedAt   time.Time
}

type EmailVerification struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Purpose    string
	TokenHash  []byte
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type Exercise struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Aka              []string
	FamilyID         uuid.UUID
	DefaultMeasure   string
	LoadSemantics    string
	IsBodyweight     bool
	Unilateral       bool
	TempoApplicable  bool
	Equipment        []string
	Summary          string
	Cues             []string
	CommonFaults     []string
	Status           string
	ContentVersionID uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ExerciseMedium struct {
	ExerciseID uuid.UUID
	MediaID    uuid.UUID
	Role       string
	OrderIndex int16
}

type Family struct {
	ID         uuid.UUID
	Slug       string
	Name       string
	OrderIndex int16
}

type IdempotencyKey struct {
	UserID             uuid.UUID
	Key                string
	RequestFingerprint []byte
	State              string
	ResponseStatus     *int32
	ResponseBody       []byte
	CreatedAt          time.Time
	CompletedAt        *time.Time
	ExpiresAt          time.Time
}

type InjuryPrehabExercise struct {
	RiskID     uuid.UUID
	ExerciseID uuid.UUID
	OrderIndex int16
}

type MediaAsset struct {
	ID             uuid.UUID
	OwnerUserID    *uuid.UUID
	Kind           string
	StorageKey     string
	Mime           string
	Bytes          int64
	Width          *int32
	Height         *int32
	DurationS      pgtype.Numeric
	PosterKey      *string
	ChecksumSha256 []byte
	Status         string
	CreatedAt      time.Time
	ReadyAt        *time.Time
	DeletedAt      *time.Time
}

type RefreshToken struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	FamilyID      uuid.UUID
	TokenHash     []byte
	DeviceID      *uuid.UUID
	IssuedAt      time.Time
	ExpiresAt     time.Time
	UsedAt        *time.Time
	RevokedAt     *time.Time
	RevokedReason *string
	ReplacedBy    *uuid.UUID
	UserAgent     *string
	Ip            *netip.Addr
}

type SessionBlock struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	SessionID       uuid.UUID
	OrderIndex      int32
	Kind            string
	RoundsPlanned   *int16
	RoundsDone      *int16
	IntervalS       *int32
	Notes           string
	ClientID        *uuid.UUID
	UpdatedAt       time.Time
	ServerUpdatedAt time.Time
	ServerSeq       int64
	DeletedAt       *time.Time
}

type SetElement struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	SessionID       uuid.UUID
	SetEntryID      uuid.UUID
	OrderIndex      int32
	ExerciseID      uuid.UUID
	Measure         string
	Reps            *int32
	HoldSeconds     pgtype.Numeric
	DistanceM       pgtype.Numeric
	Tempo           *string
	LoadKg          pgtype.Numeric
	IsEccentricOnly bool
	IsPartialRom    bool
	RomNote         *string
	FormQuality     *int16
	Failed          bool
	AssistanceClass string
	ClientID        *uuid.UUID
	UpdatedAt       time.Time
	ServerUpdatedAt time.Time
	ServerSeq       int64
	DeletedAt       *time.Time
}

type SetElementAssistance struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	SetElementID      uuid.UUID
	Type              string
	BandID            *uuid.UUID
	BandCount         int16
	Anchor            *string
	EstimatedAssistKg pgtype.Numeric
	Note              string
	ClientID          *uuid.UUID
	UpdatedAt         time.Time
	ServerUpdatedAt   time.Time
	ServerSeq         int64
	DeletedAt         *time.Time
}

type SetElementMedium struct {
	SetElementID uuid.UUID
	UserID       uuid.UUID
	MediaID      uuid.UUID
	OrderIndex   int16
	CreatedAt    time.Time
}

type SetEntry struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	SessionID         uuid.UUID
	BlockID           uuid.UUID
	OrderIndex        int32
	RoundIndex        *int16
	Kind              string
	IsPlanned         bool
	RestAfterPlannedS *int32
	RestAfterActualS  *int32
	Rpe               pgtype.Numeric
	Rir               *int16
	CompletedAt       *time.Time
	Notes             string
	ClientID          *uuid.UUID
	UpdatedAt         time.Time
	ServerUpdatedAt   time.Time
	ServerSeq         int64
	DeletedAt         *time.Time
}

type Skill struct {
	ID               uuid.UUID
	Slug             string
	FamilyID         uuid.UUID
	Name             string
	Aka              []string
	DifficultyTier   int16
	IsMilestone      bool
	Summary          string
	PrimaryMuscles   []string
	CommonFaults     []string
	MapConstellation *string
	MapX             pgtype.Numeric
	MapY             pgtype.Numeric
	Status           string
	ContentVersionID uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type SkillEdge struct {
	FromSkillLevelID uuid.UUID
	ToSkillLevelID   uuid.UUID
	Relation         string
	Weight           pgtype.Numeric
}

type SkillInjuryRisk struct {
	ID               uuid.UUID
	SkillID          uuid.UUID
	Region           string
	Name             string
	Description      string
	RiskFactors      []string
	EarlySigns       []string
	Disclaimer       string
	OrderIndex       int16
	ContentVersionID uuid.UUID
}

type SkillLevel struct {
	ID               uuid.UUID
	SkillID          uuid.UUID
	OrderIndex       int16
	Slug             string
	Name             string
	Description      string
	UnlockCriteria   []byte
	EstWeeksFromPrev *int16
	UpdatedAt        time.Time
}

type SkillLevelExercise struct {
	SkillLevelID uuid.UUID
	ExerciseID   uuid.UUID
	Role         string
	OrderIndex   int16
}

type SkillMedium struct {
	SkillID    uuid.UUID
	MediaID    uuid.UUID
	Role       string
	OrderIndex int16
}

type SkillUnlockEvent struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	SkillLevelID       uuid.UUID
	OccurredAt         time.Time
	SessionID          *uuid.UUID
	EvidenceSetEntryID *uuid.UUID
	Verification       string
	CriteriaSnapshot   []byte
}

type TemplateBlock struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	TemplateID      uuid.UUID
	OrderIndex      int32
	Kind            string
	RoundsPlanned   *int16
	IntervalS       *int32
	Notes           string
	ClientID        *uuid.UUID
	UpdatedAt       time.Time
	ServerUpdatedAt time.Time
	ServerSeq       int64
	DeletedAt       *time.Time
}

type TemplateSetElement struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	TemplateSetEntryID uuid.UUID
	OrderIndex         int32
	ExerciseID         uuid.UUID
	Measure            string
	TargetReps         *int32
	TargetHoldSeconds  pgtype.Numeric
	TargetDistanceM    pgtype.Numeric
	TargetLoadKg       pgtype.Numeric
	Tempo              *string
	ClientID           *uuid.UUID
	UpdatedAt          time.Time
	ServerUpdatedAt    time.Time
	ServerSeq          int64
	DeletedAt          *time.Time
}

type TemplateSetEntry struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	TemplateBlockID   uuid.UUID
	OrderIndex        int32
	Kind              string
	RestAfterPlannedS *int32
	TargetRpe         pgtype.Numeric
	Notes             string
	ClientID          *uuid.UUID
	UpdatedAt         time.Time
	ServerUpdatedAt   time.Time
	ServerSeq         int64
	DeletedAt         *time.Time
}

type User struct {
	ID                  uuid.UUID
	Email               *string
	EmailVerifiedAt     *time.Time
	PasswordHash        *string
	DisplayName         string
	Locale              string
	UnitSystem          string
	WeekStart           int16
	Timezone            string
	Status              string
	DeletionRequestedAt *time.Time
	SyncSeq             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           *time.Time
}

type UserBadge struct {
	UserID   uuid.UUID
	BadgeID  uuid.UUID
	EarnedAt time.Time
	RefID    *uuid.UUID
}

type UserBodyweightLog struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	MeasuredAt      time.Time
	LocalDate       pgtype.Date
	BodyweightKg    pgtype.Numeric
	Note            string
	ClientID        *uuid.UUID
	UpdatedAt       time.Time
	ServerUpdatedAt time.Time
	ServerSeq       int64
	DeletedAt       *time.Time
}

type UserExerciseBest struct {
	UserID               uuid.UUID
	ExerciseID           uuid.UUID
	Measure              string
	AssistanceClass      string
	BestValue            pgtype.Numeric
	BestLoadKg           pgtype.Numeric
	AchievedAt           time.Time
	EvidenceSetElementID *uuid.UUID
	Occurrences30d       int32
	UpdatedAt            time.Time
}

type UserSkillState struct {
	UserID             uuid.UUID
	SkillLevelID       uuid.UUID
	State              string
	BestValue          pgtype.Numeric
	BestUnit           *string
	BestAt             *time.Time
	StaleSince         *time.Time
	FirstAchievedAt    *time.Time
	EvidenceSetEntryID *uuid.UUID
	Verification       string
	AttemptsCount      int32
	UpdatedAt          time.Time
}

type UserStreak struct {
	UserID                 uuid.UUID
	CurrentDays            int32
	LongestDays            int32
	LastCountedDate        pgtype.Date
	FreezeCredits          int16
	FreezeCreditsUpdatedAt time.Time
	UpdatedAt              time.Time
}

type UserTrainingDay struct {
	UserID          uuid.UUID
	LocalDate       pgtype.Date
	SessionCount    int16
	HadSession      bool
	PlannedRest     bool
	Deload          bool
	FreezeUsed      bool
	CountsForStreak bool
}

type UserXpEvent struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Source     string
	Amount     int32
	RefType    *string
	RefID      *uuid.UUID
	OccurredAt time.Time
}

type WorkoutSession struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	StartedAt        time.Time
	EndedAt          *time.Time
	Timezone         string
	LocalDate        pgtype.Date
	Title            string
	Notes            string
	PerceivedFatigue *int16
	BodyweightKg     pgtype.Numeric
	Status           string
	IsRestDay        bool
	TemplateID       *uuid.UUID
	CompletedAt      *time.Time
	ClientID         *uuid.UUID
	UpdatedAt        time.Time
	ServerUpdatedAt  time.Time
	ServerSeq        int64
	DeletedAt        *time.Time
}

type WorkoutTemplate struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Description      string
	Visibility       string
	SourceTemplateID *uuid.UUID
	EstDurationMin   *int16
	ClientID         *uuid.UUID
	UpdatedAt        time.Time
	ServerUpdatedAt  time.Time
	ServerSeq        int64
	DeletedAt        *time.Time
}
