// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: planning.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearConstraint = `-- name: ClearConstraint :exec
UPDATE planning_constraints SET cleared_at = now() WHERE id = $1 AND user_id = $2
`

type ClearConstraintParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ClearConstraint(ctx context.Context, arg ClearConstraintParams) error {
	_, err := q.db.Exec(ctx, clearConstraint, arg.ID, arg.UserID)
	return err
}

const deleteCapacityEstimate = `-- name: DeleteCapacityEstimate :exec
DELETE FROM user_capacity_estimates WHERE user_id = $1 AND exercise = $2 AND assistance = $3
`

type DeleteCapacityEstimateParams struct {
	UserID     uuid.UUID
	Exercise   string
	Assistance string
}

func (q *Queries) DeleteCapacityEstimate(ctx context.Context, arg DeleteCapacityEstimateParams) error {
	_, err := q.db.Exec(ctx, deleteCapacityEstimate, arg.UserID, arg.Exercise, arg.Assistance)
	return err
}

const deleteLadderState = `-- name: DeleteLadderState :exec
DELETE FROM user_ladder_states WHERE user_id = $1 AND skill = $2
`

type DeleteLadderStateParams struct {
	UserID uuid.UUID
	Skill  string
}

func (q *Queries) DeleteLadderState(ctx context.Context, arg DeleteLadderStateParams) error {
	_, err := q.db.Exec(ctx, deleteLadderState, arg.UserID, arg.Skill)
	return err
}

const deleteRegionStatus = `-- name: DeleteRegionStatus :exec
DELETE FROM user_region_status WHERE user_id = $1 AND region = $2
`

type DeleteRegionStatusParams struct {
	UserID uuid.UUID
	Region string
}

func (q *Queries) DeleteRegionStatus(ctx context.Context, arg DeleteRegionStatusParams) error {
	_, err := q.db.Exec(ctx, deleteRegionStatus, arg.UserID, arg.Region)
	return err
}

const deleteScreening = `-- name: DeleteScreening :exec
DELETE FROM user_screening WHERE user_id = $1
`

func (q *Queries) DeleteScreening(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScreening, userID)
	return err
}

const deleteTrainingBreak = `-- name: DeleteTrainingBreak :exec
DELETE FROM user_training_breaks WHERE user_id = $1
`

func (q *Queries) DeleteTrainingBreak(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrainingBreak, userID)
	return err
}

const dropGoal = `-- name: DropGoal :exec
UPDATE user_goals SET status = 'dropped', priority = NULL, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type DropGoalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DropGoal(ctx context.Context, arg DropGoalParams) error {
	_, err := q.db.Exec(ctx, dropGoal, arg.ID, arg.UserID)
	return err
}

const getActivePlan = `-- name: GetActivePlan :one

SELECT id, user_id, week_start, ruleset_version, input_hash, status, payload, created_at FROM training_plans WHERE user_id = $1 AND week_start = $2 AND status = 'active'
`

type GetActivePlanParams struct {
	UserID    uuid.UUID
	WeekStart pgtype.Date
}

// ------------------------------------------------------------------- plans
func (q *Queries) GetActivePlan(ctx context.Context, arg GetActivePlanParams) (TrainingPlan, error) {
	row := q.db.QueryRow(ctx, getActivePlan, arg.UserID, arg.WeekStart)
	var i TrainingPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.RulesetVersion,
		&i.InputHash,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePlannedSession = `-- name: GetActivePlannedSession :one
SELECT p.payload, s.order_index
FROM planned_sessions s
JOIN training_plans p ON p.id = s.plan_id AND p.user_id = s.user_id
WHERE s.id = $1 AND s.user_id = $2 AND p.status = 'active'
`

type GetActivePlannedSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetActivePlannedSessionRow struct {
	Payload    []byte
	OrderIndex int32
}

func (q *Queries) GetActivePlannedSession(ctx context.Context, arg GetActivePlannedSessionParams) (GetActivePlannedSessionRow, error) {
	row := q.db.QueryRow(ctx, getActivePlannedSession, arg.ID, arg.UserID)
	var i GetActivePlannedSessionRow
	err := row.Scan(&i.Payload, &i.OrderIndex)
	return i, err
}

const getDecision = `-- name: GetDecision :one

SELECT id, user_id, trigger, source_id, occurred_at, changes FROM plan_decisions WHERE user_id = $1 AND trigger = $2 AND source_id = $3
`

type GetDecisionParams struct {
	UserID   uuid.UUID
	Trigger  string
	SourceID string
}

// --------------------------------------------------------------- decisions
func (q *Queries) GetDecision(ctx context.Context, arg GetDecisionParams) (PlanDecision, error) {
	row := q.db.QueryRow(ctx, getDecision, arg.UserID, arg.Trigger, arg.SourceID)
	var i PlanDecision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Trigger,
		&i.SourceID,
		&i.OccurredAt,
		&i.Changes,
	)
	return i, err
}

const getPlannerState = `-- name: GetPlannerState :one

SELECT user_id, meso_start, last_deload, deload_week, deload_kind, deload_next, calibrate, headroom, entry, unlocked, updated_at FROM user_planner_states WHERE user_id = $1
`

// ----------------------------------------------------- phase and bookkeeping
func (q *Queries) GetPlannerState(ctx context.Context, userID uuid.UUID) (UserPlannerState, error) {
	row := q.db.QueryRow(ctx, getPlannerState, userID)
	var i UserPlannerState
	err := row.Scan(
		&i.UserID,
		&i.MesoStart,
		&i.LastDeload,
		&i.DeloadWeek,
		&i.DeloadKind,
		&i.DeloadNext,
		&i.Calibrate,
		&i.Headroom,
		&i.Entry,
		&i.Unlocked,
		&i.UpdatedAt,
	)
	return i, err
}

const getScreening = `-- name: GetScreening :one

SELECT user_id, exertion_symptoms, any_yes, cleared, updated_at FROM user_screening WHERE user_id = $1
`

// --------------------------------------------------------------- screening
func (q *Queries) GetScreening(ctx context.Context, userID uuid.UUID) (UserScreening, error) {
	row := q.db.QueryRow(ctx, getScreening, userID)
	var i UserScreening
	err := row.Scan(
		&i.UserID,
		&i.ExertionSymptoms,
		&i.AnyYes,
		&i.Cleared,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingBreak = `-- name: GetTrainingBreak :one

SELECT user_id, days, straight_days, since, step, step_since, step_sessions, logged, reference, base, updated_at FROM user_training_breaks WHERE user_id = $1
`

// ------------------------------------------------------------------ breaks
func (q *Queries) GetTrainingBreak(ctx context.Context, userID uuid.UUID) (UserTrainingBreak, error) {
	row := q.db.QueryRow(ctx, getTrainingBreak, userID)
	var i UserTrainingBreak
	err := row.Scan(
		&i.UserID,
		&i.Days,
		&i.StraightDays,
		&i.Since,
		&i.Step,
		&i.StepSince,
		&i.StepSessions,
		&i.Logged,
		&i.Reference,
		&i.Base,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingProfile = `-- name: GetTrainingProfile :one

SELECT user_id, birth_year, sessions_per_week, session_minutes, equipment, bodyweight_kg, training_level, training_months, last_regular_training, health_data_consent, disclaimer_ack, onboarded_at, preferred_days, mobility, max_added_load_kg, smallest_plate_kg, created_at, updated_at FROM user_training_profiles WHERE user_id = $1
`

// ----------------------------------------------------------------- profile
func (q *Queries) GetTrainingProfile(ctx context.Context, userID uuid.UUID) (UserTrainingProfile, error) {
	row := q.db.QueryRow(ctx, getTrainingProfile, userID)
	var i UserTrainingProfile
	err := row.Scan(
		&i.UserID,
		&i.BirthYear,
		&i.SessionsPerWeek,
		&i.SessionMinutes,
		&i.Equipment,
		&i.BodyweightKg,
		&i.TrainingLevel,
		&i.TrainingMonths,
		&i.LastRegularTraining,
		&i.HealthDataConsent,
		&i.DisclaimerAck,
		&i.OnboardedAt,
		&i.PreferredDays,
		&i.Mobility,
		&i.MaxAddedLoadKg,
		&i.SmallestPlateKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConstraint = `-- name: InsertConstraint :exec
INSERT INTO planning_constraints (id, user_id, kind, region, created_at, position)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertConstraintParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	Region    *string
	CreatedAt time.Time
	Position  int32
}

func (q *Queries) InsertConstraint(ctx context.Context, arg InsertConstraintParams) error {
	_, err := q.db.Exec(ctx, insertConstraint,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Region,
		arg.CreatedAt,
		arg.Position,
	)
	return err
}

const insertDecision = `-- name: InsertDecision :exec
INSERT INTO plan_decisions (id, user_id, trigger, source_id, occurred_at, changes)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDecisionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Trigger    string
	SourceID   string
	OccurredAt time.Time
	Changes    []byte
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) error {
	_, err := q.db.Exec(ctx, insertDecision,
		arg.ID,
		arg.UserID,
		arg.Trigger,
		arg.SourceID,
		arg.OccurredAt,
		arg.Changes,
	)
	return err
}

const insertGoal = `-- name: InsertGoal :exec
INSERT INTO user_goals (id, user_id, skill, target_level, priority, target_date)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertGoalParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Skill       string
	TargetLevel string
	Priority    *int16
	TargetDate  *time.Time
}

func (q *Queries) InsertGoal(ctx context.Context, arg InsertGoalParams) error {
	_, err := q.db.Exec(ctx, insertGoal,
		arg.ID,
		arg.UserID,
		arg.Skill,
		arg.TargetLevel,
		arg.Priority,
		arg.TargetDate,
	)
	return err
}

const insertPainReport = `-- name: InsertPainReport :execrows
INSERT INTO user_pain_reports (
    id, user_id, region, timepoint, nrs, lasted_over_1h, persisted_over_15min, sudden_sharp,
    session_id, reported_at, position
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
`

type InsertPainReportParams struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Region             string
	Timepoint          string
	Nrs                float64
	LastedOver1h       bool
	PersistedOver15min bool
	SuddenSharp        bool
	SessionID          *uuid.UUID
	ReportedAt         time.Time
	Position           int32
}

// A report the client already wrote keeps its row.
func (q *Queries) InsertPainReport(ctx context.Context, arg InsertPainReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPainReport,
		arg.ID,
		arg.UserID,
		arg.Region,
		arg.Timepoint,
		arg.Nrs,
		arg.LastedOver1h,
		arg.PersistedOver15min,
		arg.SuddenSharp,
		arg.SessionID,
		arg.ReportedAt,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPlan = `-- name: InsertPlan :exec
INSERT INTO training_plans (id, user_id, week_start, ruleset_version, input_hash, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPlanParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	WeekStart      pgtype.Date
	RulesetVersion string
	InputHash      string
	Payload        []byte
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) error {
	_, err := q.db.Exec(ctx, insertPlan,
		arg.ID,
		arg.UserID,
		arg.WeekStart,
		arg.RulesetVersion,
		arg.InputHash,
		arg.Payload,
	)
	return err
}

const insertPlannedSession = `-- name: InsertPlannedSession :exec
INSERT INTO planned_sessions (id, user_id, plan_id, order_index, scheduled_date, kind, est_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPlannedSessionParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	PlanID        uuid.UUID
	OrderIndex    int32
	ScheduledDate pgtype.Date
	Kind          string
	EstMinutes    float64
}

func (q *Queries) InsertPlannedSession(ctx context.Context, arg InsertPlannedSessionParams) error {
	_, err := q.db.Exec(ctx, insertPlannedSession,
		arg.ID,
		arg.UserID,
		arg.PlanID,
		arg.OrderIndex,
		arg.ScheduledDate,
		arg.Kind,
		arg.EstMinutes,
	)
	return err
}

const insertPlannerSession = `-- name: InsertPlannerSession :exec
INSERT INTO planner_sessions (id, user_id, local_date, deload, fatigue, sets, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPlannerSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	LocalDate time.Time
	Deload    bool
	Fatigue   *float64
	Sets      []byte
	Position  int32
}

func (q *Queries) InsertPlannerSession(ctx context.Context, arg InsertPlannerSessionParams) error {
	_, err := q.db.Exec(ctx, insertPlannerSession,
		arg.ID,
		arg.UserID,
		arg.LocalDate,
		arg.Deload,
		arg.Fatigue,
		arg.Sets,
		arg.Position,
	)
	return err
}

const listActiveConstraints = `-- name: ListActiveConstraints :many

SELECT id, user_id, kind, region, created_at, position, cleared_at FROM planning_constraints WHERE user_id = $1 AND cleared_at IS NULL ORDER BY position
`

// ------------------------------------------------------------- constraints
func (q *Queries) ListActiveConstraints(ctx context.Context, userID uuid.UUID) ([]PlanningConstraint, error) {
	rows, err := q.db.Query(ctx, listActiveConstraints, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanningConstraint{}
	for rows.Next() {
		var i PlanningConstraint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Region,
			&i.CreatedAt,
			&i.Position,
			&i.ClearedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGoals = `-- name: ListActiveGoals :many

SELECT id, user_id, skill, target_level, priority, target_date, status, created_at, updated_at FROM user_goals WHERE user_id = $1 AND status = 'active' ORDER BY priority
`

// ------------------------------------------------------------------- goals
func (q *Queries) ListActiveGoals(ctx context.Context, userID uuid.UUID) ([]UserGoal, error) {
	rows, err := q.db.Query(ctx, listActiveGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserGoal{}
	for rows.Next() {
		var i UserGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Skill,
			&i.TargetLevel,
			&i.Priority,
			&i.TargetDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapacityEstimates = `-- name: ListCapacityEstimates :many

SELECT user_id, exercise, assistance, mu, sigma, origin, observed_at, seen_at, n_obs, pending, updated_at FROM user_capacity_estimates WHERE user_id = $1 ORDER BY exercise, assistance
`

// -------------------------------------------------------------- capacities
func (q *Queries) ListCapacityEstimates(ctx context.Context, userID uuid.UUID) ([]UserCapacityEstimate, error) {
	rows, err := q.db.Query(ctx, listCapacityEstimates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCapacityEstimate{}
	for rows.Next() {
		var i UserCapacityEstimate
		if err := rows.Scan(
			&i.UserID,
			&i.Exercise,
			&i.Assistance,
			&i.Mu,
			&i.Sigma,
			&i.Origin,
			&i.ObservedAt,
			&i.SeenAt,
			&i.NObs,
			&i.Pending,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, user_id, trigger, source_id, occurred_at, changes FROM plan_decisions
WHERE user_id = $1
  AND ($2::timestamptz IS NULL
       OR (occurred_at, id) < ($2, $3::uuid))
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type ListDecisionsParams struct {
	UserID    uuid.UUID
	CursorAt  *time.Time
	CursorID  *uuid.UUID
	PageLimit int32
}

func (q *Queries) ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]PlanDecision, error) {
	rows, err := q.db.Query(ctx, listDecisions,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanDecision{}
	for rows.Next() {
		var i PlanDecision
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Trigger,
			&i.SourceID,
			&i.OccurredAt,
			&i.Changes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLadderStates = `-- name: ListLadderStates :many

SELECT user_id, skill, rung, status, since, exposures, claimed, cap_rung, probe_offer, rep_target, load_kg, ecc_s, last_up, cap_to, cap_until, updated_at FROM user_ladder_states WHERE user_id = $1 ORDER BY skill
`

// ----------------------------------------------------------------- ladders
func (q *Queries) ListLadderStates(ctx context.Context, userID uuid.UUID) ([]UserLadderState, error) {
	rows, err := q.db.Query(ctx, listLadderStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLadderState{}
	for rows.Next() {
		var i UserLadderState
		if err := rows.Scan(
			&i.UserID,
			&i.Skill,
			&i.Rung,
			&i.Status,
			&i.Since,
			&i.Exposures,
			&i.Claimed,
			&i.CapRung,
			&i.ProbeOffer,
			&i.RepTarget,
			&i.LoadKg,
			&i.EccS,
			&i.LastUp,
			&i.CapTo,
			&i.CapUntil,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPainReports = `-- name: ListPainReports :many

SELECT id, user_id, region, timepoint, nrs, lasted_over_1h, persisted_over_15min, sudden_sharp, session_id, reported_at, position, created_at FROM user_pain_reports WHERE user_id = $1 ORDER BY position
`

// ------------------------------------------------------------ pain reports
func (q *Queries) ListPainReports(ctx context.Context, userID uuid.UUID) ([]UserPainReport, error) {
	rows, err := q.db.Query(ctx, listPainReports, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPainReport{}
	for rows.Next() {
		var i UserPainReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Region,
			&i.Timepoint,
			&i.Nrs,
			&i.LastedOver1h,
			&i.PersistedOver15min,
			&i.SuddenSharp,
			&i.SessionID,
			&i.ReportedAt,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedSessions = `-- name: ListPlannedSessions :many
SELECT id, user_id, plan_id, order_index, scheduled_date, kind, est_minutes, status, workout_session_id FROM planned_sessions WHERE plan_id = $1 AND user_id = $2 ORDER BY order_index
`

type ListPlannedSessionsParams struct {
	PlanID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListPlannedSessions(ctx context.Context, arg ListPlannedSessionsParams) ([]PlannedSession, error) {
	rows, err := q.db.Query(ctx, listPlannedSessions, arg.PlanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlannedSession{}
	for rows.Next() {
		var i PlannedSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.OrderIndex,
			&i.ScheduledDate,
			&i.Kind,
			&i.EstMinutes,
			&i.Status,
			&i.WorkoutSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannerSessions = `-- name: ListPlannerSessions :many

SELECT id, user_id, local_date, deload, fatigue, sets, position, received_at FROM planner_sessions WHERE user_id = $1 ORDER BY local_date, position
`

// ----------------------------------------------------------------- history
func (q *Queries) ListPlannerSessions(ctx context.Context, userID uuid.UUID) ([]PlannerSession, error) {
	rows, err := q.db.Query(ctx, listPlannerSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlannerSession{}
	for rows.Next() {
		var i PlannerSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocalDate,
			&i.Deload,
			&i.Fatigue,
			&i.Sets,
			&i.Position,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegionStatus = `-- name: ListRegionStatus :many

SELECT user_id, region, state, entered_via, since, start_fraction, step, step_since, step_sessions, reference, prior_injury, complaint, complaint_at, restrictions, breaches, pain_deload_to, rest_until, hold_at_ref, referral, updated_at FROM user_region_status WHERE user_id = $1 ORDER BY region
`

// ----------------------------------------------------------------- regions
func (q *Queries) ListRegionStatus(ctx context.Context, userID uuid.UUID) ([]UserRegionStatus, error) {
	rows, err := q.db.Query(ctx, listRegionStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRegionStatus{}
	for rows.Next() {
		var i UserRegionStatus
		if err := rows.Scan(
			&i.UserID,
			&i.Region,
			&i.State,
			&i.EnteredVia,
			&i.Since,
			&i.StartFraction,
			&i.Step,
			&i.StepSince,
			&i.StepSessions,
			&i.Reference,
			&i.PriorInjury,
			&i.Complaint,
			&i.ComplaintAt,
			&i.Restrictions,
			&i.Breaches,
			&i.PainDeloadTo,
			&i.RestUntil,
			&i.HoldAtRef,
			&i.Referral,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlanner = `-- name: LockPlanner :exec

SELECT pg_advisory_xact_lock(1885433198, hashtext($1::uuid::text))
`

// The training planner: snapshot parts, plans and the decision log.
// internal/store/planning.go assembles them; see ADR 0013.
// Serialises the planner calls of one user for the rest of the
// transaction. The first key names the planner, so other advisory locks
// cannot collide with it.
func (q *Queries) LockPlanner(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockPlanner, userID)
	return err
}

const nextConstraintPosition = `-- name: NextConstraintPosition :one
SELECT coalesce(max(position) + 1, 0)::int AS next FROM planning_constraints WHERE user_id = $1
`

func (q *Queries) NextConstraintPosition(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextConstraintPosition, userID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const nextPainPosition = `-- name: NextPainPosition :one
SELECT coalesce(max(position) + 1, 0)::int AS next FROM user_pain_reports WHERE user_id = $1
`

func (q *Queries) NextPainPosition(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextPainPosition, userID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const nextPlannerSessionPosition = `-- name: NextPlannerSessionPosition :one
SELECT coalesce(max(position) + 1, 0)::int AS next FROM planner_sessions WHERE user_id = $1
`

func (q *Queries) NextPlannerSessionPosition(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextPlannerSessionPosition, userID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const supersedeActivePlan = `-- name: SupersedeActivePlan :exec
UPDATE training_plans SET status = 'superseded'
WHERE user_id = $1 AND week_start = $2 AND status = 'active'
`

type SupersedeActivePlanParams struct {
	UserID    uuid.UUID
	WeekStart pgtype.Date
}

func (q *Queries) SupersedeActivePlan(ctx context.Context, arg SupersedeActivePlanParams) error {
	_, err := q.db.Exec(ctx, supersedeActivePlan, arg.UserID, arg.WeekStart)
	return err
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE user_goals SET priority = $3, target_date = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateGoalParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Priority   *int16
	TargetDate *time.Time
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.Exec(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Priority,
		arg.TargetDate,
	)
	return err
}

const upsertCapacityEstimate = `-- name: UpsertCapacityEstimate :exec
INSERT INTO user_capacity_estimates (
    user_id, exercise, assistance, mu, sigma, origin, observed_at, seen_at, n_obs, pending
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, exercise, assistance) DO UPDATE SET
    mu = EXCLUDED.mu,
    sigma = EXCLUDED.sigma,
    origin = EXCLUDED.origin,
    observed_at = EXCLUDED.observed_at,
    seen_at = EXCLUDED.seen_at,
    n_obs = EXCLUDED.n_obs,
    pending = EXCLUDED.pending,
    updated_at = now()
`

type UpsertCapacityEstimateParams struct {
	UserID     uuid.UUID
	Exercise   string
	Assistance string
	Mu         float64
	Sigma      float64
	Origin     string
	ObservedAt *time.Time
	SeenAt     *time.Time
	NObs       int32
	Pending    *float64
}

func (q *Queries) UpsertCapacityEstimate(ctx context.Context, arg UpsertCapacityEstimateParams) error {
	_, err := q.db.Exec(ctx, upsertCapacityEstimate,
		arg.UserID,
		arg.Exercise,
		arg.Assistance,
		arg.Mu,
		arg.Sigma,
		arg.Origin,
		arg.ObservedAt,
		arg.SeenAt,
		arg.NObs,
		arg.Pending,
	)
	return err
}

const upsertLadderState = `-- name: UpsertLadderState :exec
INSERT INTO user_ladder_states (
    user_id, skill, rung, status, since, exposures, claimed, cap_rung, probe_offer, rep_target,
    load_kg, ecc_s, last_up, cap_to, cap_until
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (user_id, skill) DO UPDATE SET
    rung = EXCLUDED.rung,
    status = EXCLUDED.status,
    since = EXCLUDED.since,
    exposures = EXCLUDED.exposures,
    claimed = EXCLUDED.claimed,
    cap_rung = EXCLUDED.cap_rung,
    probe_offer = EXCLUDED.probe_offer,
    rep_target = EXCLUDED.rep_target,
    load_kg = EXCLUDED.load_kg,
    ecc_s = EXCLUDED.ecc_s,
    last_up = EXCLUDED.last_up,
    cap_to = EXCLUDED.cap_to,
    cap_until = EXCLUDED.cap_until,
    updated_at = now()
`

type UpsertLadderStateParams struct {
	UserID     uuid.UUID
	Skill      string
	Rung       *string
	Status     *string
	Since      *time.Time
	Exposures  int32
	Claimed    *string
	CapRung    *string
	ProbeOffer bool
	RepTarget  float64
	LoadKg     float64
	EccS       float64
	LastUp     *time.Time
	CapTo      *string
	CapUntil   *time.Time
}

func (q *Queries) UpsertLadderState(ctx context.Context, arg UpsertLadderStateParams) error {
	_, err := q.db.Exec(ctx, upsertLadderState,
		arg.UserID,
		arg.Skill,
		arg.Rung,
		arg.Status,
		arg.Since,
		arg.Exposures,
		arg.Claimed,
		arg.CapRung,
		arg.ProbeOffer,
		arg.RepTarget,
		arg.LoadKg,
		arg.EccS,
		arg.LastUp,
		arg.CapTo,
		arg.CapUntil,
	)
	return err
}

const upsertPlannerState = `-- name: UpsertPlannerState :exec
INSERT INTO user_planner_states (
    user_id, meso_start, last_deload, deload_week, deload_kind, deload_next, calibrate,
    headroom, entry, unlocked
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id) DO UPDATE SET
    meso_start = EXCLUDED.meso_start,
    last_deload = EXCLUDED.last_deload,
    deload_week = EXCLUDED.deload_week,
    deload_kind = EXCLUDED.deload_kind,
    deload_next = EXCLUDED.deload_next,
    calibrate = EXCLUDED.calibrate,
    headroom = EXCLUDED.headroom,
    entry = EXCLUDED.entry,
    unlocked = EXCLUDED.unlocked,
    updated_at = now()
`

type UpsertPlannerStateParams struct {
	UserID     uuid.UUID
	MesoStart  *time.Time
	LastDeload *time.Time
	DeloadWeek *time.Time
	DeloadKind *string
	DeloadNext *string
	Calibrate  []string
	Headroom   []byte
	Entry      []byte
	Unlocked   []byte
}

func (q *Queries) UpsertPlannerState(ctx context.Context, arg UpsertPlannerStateParams) error {
	_, err := q.db.Exec(ctx, upsertPlannerState,
		arg.UserID,
		arg.MesoStart,
		arg.LastDeload,
		arg.DeloadWeek,
		arg.DeloadKind,
		arg.DeloadNext,
		arg.Calibrate,
		arg.Headroom,
		arg.Entry,
		arg.Unlocked,
	)
	return err
}

const upsertRegionStatus = `-- name: UpsertRegionStatus :exec
INSERT INTO user_region_status (
    user_id, region, state, entered_via, since, start_fraction, step, step_since, step_sessions,
    reference, prior_injury, complaint, complaint_at, restrictions, breaches, pain_deload_to,
    rest_until, hold_at_ref, referral
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (user_id, region) DO UPDATE SET
    state = EXCLUDED.state,
    entered_via = EXCLUDED.entered_via,
    since = EXCLUDED.since,
    start_fraction = EXCLUDED.start_fraction,
    step = EXCLUDED.step,
    step_since = EXCLUDED.step_since,
    step_sessions = EXCLUDED.step_sessions,
    reference = EXCLUDED.reference,
    prior_injury = EXCLUDED.prior_injury,
    complaint = EXCLUDED.complaint,
    complaint_at = EXCLUDED.complaint_at,
    restrictions = EXCLUDED.restrictions,
    breaches = EXCLUDED.breaches,
    pain_deload_to = EXCLUDED.pain_deload_to,
    rest_until = EXCLUDED.rest_until,
    hold_at_ref = EXCLUDED.hold_at_ref,
    referral = EXCLUDED.referral,
    updated_at = now()
`

type UpsertRegionStatusParams struct {
	UserID        uuid.UUID
	Region        string
	State         string
	EnteredVia    *string
	Since         *time.Time
	StartFraction float64
	Step          int16
	StepSince     *time.Time
	StepSessions  int32
	Reference     []byte
	PriorInjury   bool
	Complaint     bool
	ComplaintAt   *time.Time
	Restrictions  []string
	Breaches      []time.Time
	PainDeloadTo  *time.Time
	RestUntil     *time.Time
	HoldAtRef     bool
	Referral      *string
}

func (q *Queries) UpsertRegionStatus(ctx context.Context, arg UpsertRegionStatusParams) error {
	_, err := q.db.Exec(ctx, upsertRegionStatus,
		arg.UserID,
		arg.Region,
		arg.State,
		arg.EnteredVia,
		arg.Since,
		arg.StartFraction,
		arg.Step,
		arg.StepSince,
		arg.StepSessions,
		arg.Reference,
		arg.PriorInjury,
		arg.Complaint,
		arg.ComplaintAt,
		arg.Restrictions,
		arg.Breaches,
		arg.PainDeloadTo,
		arg.RestUntil,
		arg.HoldAtRef,
		arg.Referral,
	)
	return err
}

const upsertScreening = `-- name: UpsertScreening :exec
INSERT INTO user_screening (user_id, exertion_symptoms, any_yes, cleared)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    exertion_symptoms = EXCLUDED.exertion_symptoms,
    any_yes = EXCLUDED.any_yes,
    cleared = EXCLUDED.cleared,
    updated_at = now()
`

type UpsertScreeningParams struct {
	UserID           uuid.UUID
	ExertionSymptoms bool
	AnyYes           bool
	Cleared          bool
}

func (q *Queries) UpsertScreening(ctx context.Context, arg UpsertScreeningParams) error {
	_, err := q.db.Exec(ctx, upsertScreening,
		arg.UserID,
		arg.ExertionSymptoms,
		arg.AnyYes,
		arg.Cleared,
	)
	return err
}

const upsertTrainingBreak = `-- name: UpsertTrainingBreak :exec
INSERT INTO user_training_breaks (
    user_id, days, straight_days, since, step, step_since, step_sessions, logged, reference, base
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id) DO UPDATE SET
    days = EXCLUDED.days,
    straight_days = EXCLUDED.straight_days,
    since = EXCLUDED.since,
    step = EXCLUDED.step,
    step_since = EXCLUDED.step_since,
    step_sessions = EXCLUDED.step_sessions,
    logged = EXCLUDED.logged,
    reference = EXCLUDED.reference,
    base = EXCLUDED.base,
    updated_at = now()
`

type UpsertTrainingBreakParams struct {
	UserID       uuid.UUID
	Days         float64
	StraightDays float64
	Since        *time.Time
	Step         int16
	StepSince    *time.Time
	StepSessions int32
	Logged       bool
	Reference    []byte
	Base         []byte
}

func (q *Queries) UpsertTrainingBreak(ctx context.Context, arg UpsertTrainingBreakParams) error {
	_, err := q.db.Exec(ctx, upsertTrainingBreak,
		arg.UserID,
		arg.Days,
		arg.StraightDays,
		arg.Since,
		arg.Step,
		arg.StepSince,
		arg.StepSessions,
		arg.Logged,
		arg.Reference,
		arg.Base,
	)
	return err
}

const upsertTrainingProfile = `-- name: UpsertTrainingProfile :exec
INSERT INTO user_training_profiles (
    user_id, birth_year, sessions_per_week, session_minutes, equipment, bodyweight_kg,
    training_level, training_months, last_regular_training, health_data_consent,
    disclaimer_ack, onboarded_at, preferred_days, mobility, max_added_load_kg, smallest_plate_kg
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (user_id) DO UPDATE SET
    birth_year = EXCLUDED.birth_year,
    sessions_per_week = EXCLUDED.sessions_per_week,
    session_minutes = EXCLUDED.session_minutes,
    equipment = EXCLUDED.equipment,
    bodyweight_kg = EXCLUDED.bodyweight_kg,
    training_level = EXCLUDED.training_level,
    training_months = EXCLUDED.training_months,
    last_regular_training = EXCLUDED.last_regular_training,
    health_data_consent = EXCLUDED.health_data_consent,
    disclaimer_ack = EXCLUDED.disclaimer_ack,
    onboarded_at = EXCLUDED.onboarded_at,
    preferred_days = EXCLUDED.preferred_days,
    mobility = EXCLUDED.mobility,
    max_added_load_kg = EXCLUDED.max_added_load_kg,
    smallest_plate_kg = EXCLUDED.smallest_plate_kg,
    updated_at = now()
`

type UpsertTrainingProfileParams struct {
	UserID              uuid.UUID
	BirthYear           int16
	SessionsPerWeek     int16
	SessionMinutes      int16
	Equipment           []string
	BodyweightKg        float64
	TrainingLevel       string
	TrainingMonths      float64
	LastRegularTraining *string
	HealthDataConsent   bool
	DisclaimerAck       bool
	OnboardedAt         time.Time
	PreferredDays       []int16
	Mobility            []byte
	MaxAddedLoadKg      float64
	SmallestPlateKg     float64
}

func (q *Queries) UpsertTrainingProfile(ctx context.Context, arg UpsertTrainingProfileParams) error {
	_, err := q.db.Exec(ctx, upsertTrainingProfile,
		arg.UserID,
		arg.BirthYear,
		arg.SessionsPerWeek,
		arg.SessionMinutes,
		arg.Equipment,
		arg.BodyweightKg,
		arg.TrainingLevel,
		arg.TrainingMonths,
		arg.LastRegularTraining,
		arg.HealthDataConsent,
		arg.DisclaimerAck,
		arg.OnboardedAt,
		arg.PreferredDays,
		arg.Mobility,
		arg.MaxAddedLoadKg,
		arg.SmallestPlateKg,
	)
	return err
}
