// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: progress.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearFreezes = `-- name: ClearFreezes :exec
UPDATE user_training_days SET freeze_used = false WHERE user_id = $1 AND freeze_used
`

// Freezes are recomputed from scratch: clear the old ones, then mark the
// days the current walk bridged.
func (q *Queries) ClearFreezes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearFreezes, userID)
	return err
}

const completedSessionsOnDay = `-- name: CompletedSessionsOnDay :one
SELECT count(*)::int FROM workout_sessions
WHERE user_id = $1 AND local_date = $2 AND status = 'completed'
  AND deleted_at IS NULL AND id <> $3
`

type CompletedSessionsOnDayParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
	ExceptID  uuid.UUID
}

func (q *Queries) CompletedSessionsOnDay(ctx context.Context, arg CompletedSessionsOnDayParams) (int32, error) {
	row := q.db.QueryRow(ctx, completedSessionsOnDay, arg.UserID, arg.LocalDate, arg.ExceptID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countedDays = `-- name: CountedDays :many
SELECT local_date FROM user_training_days
WHERE user_id = $1 AND (had_session OR planned_rest OR deload)
ORDER BY local_date
`

// Days that count on their own merit. Freeze days are not included: which
// days a freeze bridges is recomputed from these every time.
func (q *Queries) CountedDays(ctx context.Context, userID uuid.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, countedDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var local_date pgtype.Date
		if err := rows.Scan(&local_date); err != nil {
			return nil, err
		}
		items = append(items, local_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEmptyFreezeDays = `-- name: DeleteEmptyFreezeDays :exec
DELETE FROM user_training_days
WHERE user_id = $1 AND NOT (had_session OR planned_rest OR deload OR freeze_used)
`

func (q *Queries) DeleteEmptyFreezeDays(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmptyFreezeDays, userID)
	return err
}

const getGraphSkill = `-- name: GetGraphSkill :one
SELECT sk.id, sk.slug, sk.name, sk.aka, sk.difficulty_tier, sk.is_milestone, sk.summary, sk.primary_muscles, sk.common_faults, sk.map_constellation, sk.map_x, sk.map_y, sk.status, f.slug AS family_slug
FROM skills sk JOIN families f ON f.id = sk.family_id
WHERE sk.slug = $1 AND sk.status <> 'retired'
`

type GetGraphSkillRow struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Aka              []string
	DifficultyTier   int16
	IsMilestone      bool
	Summary          string
	PrimaryMuscles   []string
	CommonFaults     []string
	MapConstellation *string
	MapX             pgtype.Numeric
	MapY             pgtype.Numeric
	Status           string
	FamilySlug       string
}

func (q *Queries) GetGraphSkill(ctx context.Context, slug string) (GetGraphSkillRow, error) {
	row := q.db.QueryRow(ctx, getGraphSkill, slug)
	var i GetGraphSkillRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Aka,
		&i.DifficultyTier,
		&i.IsMilestone,
		&i.Summary,
		&i.PrimaryMuscles,
		&i.CommonFaults,
		&i.MapConstellation,
		&i.MapX,
		&i.MapY,
		&i.Status,
		&i.FamilySlug,
	)
	return i, err
}

const getStreak = `-- name: GetStreak :one
SELECT user_id, current_days, longest_days, last_counted_date, freeze_credits, freeze_credits_updated_at, updated_at FROM user_streaks WHERE user_id = $1
`

func (q *Queries) GetStreak(ctx context.Context, userID uuid.UUID) (UserStreak, error) {
	row := q.db.QueryRow(ctx, getStreak, userID)
	var i UserStreak
	err := row.Scan(
		&i.UserID,
		&i.CurrentDays,
		&i.LongestDays,
		&i.LastCountedDate,
		&i.FreezeCredits,
		&i.FreezeCreditsUpdatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnlockEvent = `-- name: GetUnlockEvent :one
SELECT id, user_id, skill_level_id, occurred_at, session_id, evidence_set_entry_id, verification, criteria_snapshot FROM skill_unlock_events WHERE user_id = $1 AND skill_level_id = $2
`

type GetUnlockEventParams struct {
	UserID       uuid.UUID
	SkillLevelID uuid.UUID
}

func (q *Queries) GetUnlockEvent(ctx context.Context, arg GetUnlockEventParams) (SkillUnlockEvent, error) {
	row := q.db.QueryRow(ctx, getUnlockEvent, arg.UserID, arg.SkillLevelID)
	var i SkillUnlockEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillLevelID,
		&i.OccurredAt,
		&i.SessionID,
		&i.EvidenceSetEntryID,
		&i.Verification,
		&i.CriteriaSnapshot,
	)
	return i, err
}

const getUserSkillState = `-- name: GetUserSkillState :one
SELECT user_id, skill_level_id, state, best_value, best_unit, best_at, stale_since, first_achieved_at, evidence_set_entry_id, verification, attempts_count, updated_at FROM user_skill_states WHERE user_id = $1 AND skill_level_id = $2
`

type GetUserSkillStateParams struct {
	UserID       uuid.UUID
	SkillLevelID uuid.UUID
}

func (q *Queries) GetUserSkillState(ctx context.Context, arg GetUserSkillStateParams) (UserSkillState, error) {
	row := q.db.QueryRow(ctx, getUserSkillState, arg.UserID, arg.SkillLevelID)
	var i UserSkillState
	err := row.Scan(
		&i.UserID,
		&i.SkillLevelID,
		&i.State,
		&i.BestValue,
		&i.BestUnit,
		&i.BestAt,
		&i.StaleSince,
		&i.FirstAchievedAt,
		&i.EvidenceSetEntryID,
		&i.Verification,
		&i.AttemptsCount,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUnlockEvent = `-- name: InsertUnlockEvent :exec
INSERT INTO skill_unlock_events (
    id, user_id, skill_level_id, occurred_at, session_id, evidence_set_entry_id,
    verification, criteria_snapshot
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
)
ON CONFLICT (user_id, skill_level_id) DO NOTHING
`

type InsertUnlockEventParams struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	SkillLevelID       uuid.UUID
	OccurredAt         time.Time
	SessionID          *uuid.UUID
	EvidenceSetEntryID *uuid.UUID
	Verification       string
	CriteriaSnapshot   []byte
}

func (q *Queries) InsertUnlockEvent(ctx context.Context, arg InsertUnlockEventParams) error {
	_, err := q.db.Exec(ctx, insertUnlockEvent,
		arg.ID,
		arg.UserID,
		arg.SkillLevelID,
		arg.OccurredAt,
		arg.SessionID,
		arg.EvidenceSetEntryID,
		arg.Verification,
		arg.CriteriaSnapshot,
	)
	return err
}

const insertXPEvent = `-- name: InsertXPEvent :one

INSERT INTO user_xp_events (id, user_id, source, amount, ref_type, ref_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, source, ref_type, ref_id) DO NOTHING
RETURNING amount
`

type InsertXPEventParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Source     string
	Amount     int32
	RefType    *string
	RefID      *uuid.UUID
	OccurredAt time.Time
}

// ------------------------------------------------------------------- xp
func (q *Queries) InsertXPEvent(ctx context.Context, arg InsertXPEventParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertXPEvent,
		arg.ID,
		arg.UserID,
		arg.Source,
		arg.Amount,
		arg.RefType,
		arg.RefID,
		arg.OccurredAt,
	)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}

const listGraphEdges = `-- name: ListGraphEdges :many
SELECT from_skill_level_id, to_skill_level_id, relation, weight
FROM skill_edges
ORDER BY to_skill_level_id, from_skill_level_id, relation
`

func (q *Queries) ListGraphEdges(ctx context.Context) ([]SkillEdge, error) {
	rows, err := q.db.Query(ctx, listGraphEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillEdge{}
	for rows.Next() {
		var i SkillEdge
		if err := rows.Scan(
			&i.FromSkillLevelID,
			&i.ToSkillLevelID,
			&i.Relation,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphLevelExercises = `-- name: ListGraphLevelExercises :many
SELECT le.skill_level_id, le.exercise_id, e.slug, le.role
FROM skill_level_exercises le JOIN exercises e ON e.id = le.exercise_id
ORDER BY le.skill_level_id, le.order_index, e.slug
`

type ListGraphLevelExercisesRow struct {
	SkillLevelID uuid.UUID
	ExerciseID   uuid.UUID
	Slug         string
	Role         string
}

func (q *Queries) ListGraphLevelExercises(ctx context.Context) ([]ListGraphLevelExercisesRow, error) {
	rows, err := q.db.Query(ctx, listGraphLevelExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphLevelExercisesRow{}
	for rows.Next() {
		var i ListGraphLevelExercisesRow
		if err := rows.Scan(
			&i.SkillLevelID,
			&i.ExerciseID,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphLevels = `-- name: ListGraphLevels :many
SELECT l.id, l.skill_id, l.order_index, l.slug, l.name, l.description, l.unlock_criteria,
       l.est_weeks_from_prev, s.slug AS skill_slug, s.name AS skill_name,
       s.difficulty_tier, s.status AS skill_status
FROM skill_levels l JOIN skills s ON s.id = l.skill_id
ORDER BY s.slug, l.order_index
`

type ListGraphLevelsRow struct {
	ID               uuid.UUID
	SkillID          uuid.UUID
	OrderIndex       int16
	Slug             string
	Name             string
	Description      string
	UnlockCriteria   []byte
	EstWeeksFromPrev *int16
	SkillSlug        string
	SkillName        string
	DifficultyTier   int16
	SkillStatus      string
}

// Every level of every skill, retired or not: prerequisites may point at a
// retired skill's level, and unlocks on them still stand.
func (q *Queries) ListGraphLevels(ctx context.Context) ([]ListGraphLevelsRow, error) {
	rows, err := q.db.Query(ctx, listGraphLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphLevelsRow{}
	for rows.Next() {
		var i ListGraphLevelsRow
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.OrderIndex,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.UnlockCriteria,
			&i.EstWeeksFromPrev,
			&i.SkillSlug,
			&i.SkillName,
			&i.DifficultyTier,
			&i.SkillStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphSkills = `-- name: ListGraphSkills :many


SELECT sk.id, sk.slug, sk.name, sk.aka, sk.difficulty_tier, sk.is_milestone, sk.summary, sk.primary_muscles, sk.common_faults, sk.map_constellation, sk.map_x, sk.map_y, sk.status, f.slug AS family_slug
FROM skills sk JOIN families f ON f.id = sk.family_id
WHERE sk.status <> 'retired'
ORDER BY sk.slug
`

type ListGraphSkillsRow struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Aka              []string
	DifficultyTier   int16
	IsMilestone      bool
	Summary          string
	PrimaryMuscles   []string
	CommonFaults     []string
	MapConstellation *string
	MapX             pgtype.Numeric
	MapY             pgtype.Numeric
	Status           string
	FamilySlug       string
}

// The skill graph, user progress, XP and streaks.
// ----------------------------------------------------------------- graph
func (q *Queries) ListGraphSkills(ctx context.Context) ([]ListGraphSkillsRow, error) {
	rows, err := q.db.Query(ctx, listGraphSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGraphSkillsRow{}
	for rows.Next() {
		var i ListGraphSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Aka,
			&i.DifficultyTier,
			&i.IsMilestone,
			&i.Summary,
			&i.PrimaryMuscles,
			&i.CommonFaults,
			&i.MapConstellation,
			&i.MapX,
			&i.MapY,
			&i.Status,
			&i.FamilySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInjuryPrehab = `-- name: ListInjuryPrehab :many
SELECT p.risk_id, p.exercise_id, e.slug
FROM injury_prehab_exercises p
JOIN exercises e ON e.id = p.exercise_id
JOIN skill_injury_risks r ON r.id = p.risk_id
WHERE r.skill_id = $1
ORDER BY p.risk_id, p.order_index
`

type ListInjuryPrehabRow struct {
	RiskID     uuid.UUID
	ExerciseID uuid.UUID
	Slug       string
}

func (q *Queries) ListInjuryPrehab(ctx context.Context, skillID uuid.UUID) ([]ListInjuryPrehabRow, error) {
	rows, err := q.db.Query(ctx, listInjuryPrehab, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInjuryPrehabRow{}
	for rows.Next() {
		var i ListInjuryPrehabRow
		if err := rows.Scan(&i.RiskID, &i.ExerciseID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillInjuries = `-- name: ListSkillInjuries :many
SELECT id, skill_id, region, name, description, risk_factors, early_signs, disclaimer, order_index, content_version_id FROM skill_injury_risks WHERE skill_id = $1 ORDER BY order_index, name
`

func (q *Queries) ListSkillInjuries(ctx context.Context, skillID uuid.UUID) ([]SkillInjuryRisk, error) {
	rows, err := q.db.Query(ctx, listSkillInjuries, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillInjuryRisk{}
	for rows.Next() {
		var i SkillInjuryRisk
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.Region,
			&i.Name,
			&i.Description,
			&i.RiskFactors,
			&i.EarlySigns,
			&i.Disclaimer,
			&i.OrderIndex,
			&i.ContentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlockEventsForSession = `-- name: ListUnlockEventsForSession :many
SELECT id, user_id, skill_level_id, occurred_at, session_id, evidence_set_entry_id, verification, criteria_snapshot FROM skill_unlock_events
WHERE user_id = $1 AND session_id = $2
ORDER BY occurred_at, id
`

type ListUnlockEventsForSessionParams struct {
	UserID    uuid.UUID
	SessionID *uuid.UUID
}

func (q *Queries) ListUnlockEventsForSession(ctx context.Context, arg ListUnlockEventsForSessionParams) ([]SkillUnlockEvent, error) {
	rows, err := q.db.Query(ctx, listUnlockEventsForSession, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillUnlockEvent{}
	for rows.Next() {
		var i SkillUnlockEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkillLevelID,
			&i.OccurredAt,
			&i.SessionID,
			&i.EvidenceSetEntryID,
			&i.Verification,
			&i.CriteriaSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSkillStates = `-- name: ListUserSkillStates :many

SELECT user_id, skill_level_id, state, best_value, best_unit, best_at, stale_since, first_achieved_at, evidence_set_entry_id, verification, attempts_count, updated_at FROM user_skill_states WHERE user_id = $1
`

// ----------------------------------------------------------- user state
func (q *Queries) ListUserSkillStates(ctx context.Context, userID uuid.UUID) ([]UserSkillState, error) {
	rows, err := q.db.Query(ctx, listUserSkillStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSkillState{}
	for rows.Next() {
		var i UserSkillState
		if err := rows.Scan(
			&i.UserID,
			&i.SkillLevelID,
			&i.State,
			&i.BestValue,
			&i.BestUnit,
			&i.BestAt,
			&i.StaleSince,
			&i.FirstAchievedAt,
			&i.EvidenceSetEntryID,
			&i.Verification,
			&i.AttemptsCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserProgress = `-- name: LockUserProgress :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockUserProgress(ctx context.Context, userKey string) error {
	_, err := q.db.Exec(ctx, lockUserProgress, userKey)
	return err
}

const markFreezeDays = `-- name: MarkFreezeDays :exec
INSERT INTO user_training_days AS d (user_id, local_date, freeze_used)
SELECT $1, unnest($2::date[]), true
ON CONFLICT (user_id, local_date) DO UPDATE SET freeze_used = true
`

type MarkFreezeDaysParams struct {
	UserID uuid.UUID
	Days   []pgtype.Date
}

func (q *Queries) MarkFreezeDays(ctx context.Context, arg MarkFreezeDaysParams) error {
	_, err := q.db.Exec(ctx, markFreezeDays, arg.UserID, arg.Days)
	return err
}

const markTrainingDay = `-- name: MarkTrainingDay :exec

INSERT INTO user_training_days AS d (user_id, local_date, session_count, had_session, planned_rest)
VALUES ($1, $2, 1, $3, $4)
ON CONFLICT (user_id, local_date) DO UPDATE SET
    session_count = d.session_count + 1,
    had_session = d.had_session OR EXCLUDED.had_session,
    planned_rest = d.planned_rest OR EXCLUDED.planned_rest
`

type MarkTrainingDayParams struct {
	UserID      uuid.UUID
	LocalDate   pgtype.Date
	HadSession  bool
	PlannedRest bool
}

// --------------------------------------------------------------- streaks
func (q *Queries) MarkTrainingDay(ctx context.Context, arg MarkTrainingDayParams) error {
	_, err := q.db.Exec(ctx, markTrainingDay,
		arg.UserID,
		arg.LocalDate,
		arg.HadSession,
		arg.PlannedRest,
	)
	return err
}

const observationsForExercises = `-- name: ObservationsForExercises :many

SELECT el.set_entry_id, el.session_id, e.slug AS exercise, el.measure,
       el.reps, el.hold_seconds, el.distance_m, el.load_kg, el.assistance_class,
       el.form_quality, el.failed, el.is_partial_rom, el.is_eccentric_only,
       COALESCE(se.completed_at, ws.started_at)::timestamptz AS performed_at
FROM set_elements el
JOIN exercises e ON e.id = el.exercise_id
JOIN set_entries se ON se.id = el.set_entry_id
JOIN workout_sessions ws ON ws.id = el.session_id
WHERE el.user_id = $1
  AND e.slug = ANY($2::text[])
  AND el.deleted_at IS NULL AND se.deleted_at IS NULL AND ws.deleted_at IS NULL
  AND NOT se.is_planned
  AND ws.status = 'completed'
`

type ObservationsForExercisesParams struct {
	UserID uuid.UUID
	Slugs  []string
}

type ObservationsForExercisesRow struct {
	SetEntryID      uuid.UUID
	SessionID       uuid.UUID
	Exercise        string
	Measure         string
	Reps            *int32
	HoldSeconds     pgtype.Numeric
	DistanceM       pgtype.Numeric
	LoadKg          pgtype.Numeric
	AssistanceClass string
	FormQuality     *int16
	Failed          bool
	IsPartialRom    bool
	IsEccentricOnly bool
	PerformedAt     time.Time
}

// ----------------------------------------------------------------- history
// Every performed element of the named exercises, from completed sessions.
// Planned sets, deleted rows and abandoned or draft sessions are not evidence.
func (q *Queries) ObservationsForExercises(ctx context.Context, arg ObservationsForExercisesParams) ([]ObservationsForExercisesRow, error) {
	rows, err := q.db.Query(ctx, observationsForExercises, arg.UserID, arg.Slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationsForExercisesRow{}
	for rows.Next() {
		var i ObservationsForExercisesRow
		if err := rows.Scan(
			&i.SetEntryID,
			&i.SessionID,
			&i.Exercise,
			&i.Measure,
			&i.Reps,
			&i.HoldSeconds,
			&i.DistanceM,
			&i.LoadKg,
			&i.AssistanceClass,
			&i.FormQuality,
			&i.Failed,
			&i.IsPartialRom,
			&i.IsEccentricOnly,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionPerformance = `-- name: SessionPerformance :one
SELECT
    count(*) FILTER (WHERE el.reps IS NOT NULL OR el.hold_seconds IS NOT NULL
                        OR el.distance_m IS NOT NULL OR el.measure = 'none')::int AS performed_elements,
    COALESCE(array_agg(el.form_quality) FILTER (WHERE el.form_quality IS NOT NULL), '{}')::smallint[] AS form_ratings
FROM set_elements el
JOIN set_entries se ON se.id = el.set_entry_id
WHERE el.session_id = $1 AND el.user_id = $2
  AND el.deleted_at IS NULL AND se.deleted_at IS NULL AND NOT se.is_planned
`

type SessionPerformanceParams struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
}

type SessionPerformanceRow struct {
	PerformedElements int32
	FormRatings       []int16
}

func (q *Queries) SessionPerformance(ctx context.Context, arg SessionPerformanceParams) (SessionPerformanceRow, error) {
	row := q.db.QueryRow(ctx, sessionPerformance, arg.SessionID, arg.UserID)
	var i SessionPerformanceRow
	err := row.Scan(&i.PerformedElements, &i.FormRatings)
	return i, err
}

const totalXP = `-- name: TotalXP :one
SELECT COALESCE(sum(amount), 0)::int FROM user_xp_events WHERE user_id = $1
`

func (q *Queries) TotalXP(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, totalXP, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertStreak = `-- name: UpsertStreak :exec
INSERT INTO user_streaks AS s (user_id, current_days, longest_days, last_counted_date, freeze_credits, freeze_credits_updated_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (user_id) DO UPDATE SET
    current_days = EXCLUDED.current_days, longest_days = EXCLUDED.longest_days,
    last_counted_date = EXCLUDED.last_counted_date,
    freeze_credits = EXCLUDED.freeze_credits,
    freeze_credits_updated_at = CASE WHEN s.freeze_credits <> EXCLUDED.freeze_credits THEN now() ELSE s.freeze_credits_updated_at END,
    updated_at = now()
`

type UpsertStreakParams struct {
	UserID          uuid.UUID
	CurrentDays     int32
	LongestDays     int32
	LastCountedDate pgtype.Date
	FreezeCredits   int16
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) error {
	_, err := q.db.Exec(ctx, upsertStreak,
		arg.UserID,
		arg.CurrentDays,
		arg.LongestDays,
		arg.LastCountedDate,
		arg.FreezeCredits,
	)
	return err
}

const upsertUserSkillState = `-- name: UpsertUserSkillState :exec
INSERT INTO user_skill_states AS u (
    user_id, skill_level_id, state, best_value, best_unit, best_at, stale_since,
    first_achieved_at, evidence_set_entry_id, verification, attempts_count, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, now()
)
ON CONFLICT (user_id, skill_level_id) DO UPDATE SET
    state = EXCLUDED.state,
    best_value = EXCLUDED.best_value, best_unit = EXCLUDED.best_unit, best_at = EXCLUDED.best_at,
    stale_since = EXCLUDED.stale_since, attempts_count = EXCLUDED.attempts_count,
    first_achieved_at = COALESCE(u.first_achieved_at, EXCLUDED.first_achieved_at),
    evidence_set_entry_id = COALESCE(u.evidence_set_entry_id, EXCLUDED.evidence_set_entry_id),
    verification = CASE WHEN u.first_achieved_at IS NULL THEN EXCLUDED.verification ELSE u.verification END,
    updated_at = now()
WHERE (u.state, u.best_value, u.best_unit, u.stale_since, u.attempts_count)
      IS DISTINCT FROM
      (EXCLUDED.state, EXCLUDED.best_value, EXCLUDED.best_unit, EXCLUDED.stale_since, EXCLUDED.attempts_count)
`

type UpsertUserSkillStateParams struct {
	UserID             uuid.UUID
	SkillLevelID       uuid.UUID
	State              string
	BestValue          pgtype.Numeric
	BestUnit           *string
	BestAt             *time.Time
	StaleSince         *time.Time
	FirstAchievedAt    *time.Time
	EvidenceSetEntryID *uuid.UUID
	Verification       string
	AttemptsCount      int32
}

// first_achieved_at, evidence and verification are only ever set once: the
// COALESCEs keep them, and the monotonic trigger refuses anything else.
func (q *Queries) UpsertUserSkillState(ctx context.Context, arg UpsertUserSkillStateParams) error {
	_, err := q.db.Exec(ctx, upsertUserSkillState,
		arg.UserID,
		arg.SkillLevelID,
		arg.State,
		arg.BestValue,
		arg.BestUnit,
		arg.BestAt,
		arg.StaleSince,
		arg.FirstAchievedAt,
		arg.EvidenceSetEntryID,
		arg.Verification,
		arg.AttemptsCount,
	)
	return err
}
