// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteAllSkillEdges(ctx context.Context) error
	DeleteInjuryPrehab(ctx context.Context, riskID uuid.UUID) error
	// Injury content references no user rows, so entries gone from a skill file
	// are deleted outright.
	DeleteInjuryRisksNotIn(ctx context.Context, arg DeleteInjuryRisksNotInParams) error
	// Associations carry no user data, so they are replaced wholesale.
	DeleteSkillLevelExercises(ctx context.Context, skillLevelID uuid.UUID) error
	// Belt and braces for deviation D-7: contentlint already rejected cycles, but
	// the seed re-checks the graph as the database now holds it. Returns the ids
	// of levels that can reach themselves through prerequisite edges.
	FindPrerequisiteCycles(ctx context.Context) ([]uuid.UUID, error)
	// Content import (cmd/seed). Every upsert is keyed on slug and leaves a row
	// untouched — updated_at and content_version_id included — when nothing in it
	// changed. The CTE returns the id whether the row was inserted, updated or
	// left alone: the INSERT returns nothing when its WHERE suppresses the update,
	// and the plain SELECT sees the pre-statement snapshot, so exactly one side
	// yields the id.
	// The newest version is what the database currently holds; its checksum is
	// the /v1/skills ETag.
	GetLatestContentVersion(ctx context.Context) (ContentVersion, error)
	InsertContentVersion(ctx context.Context, arg InsertContentVersionParams) error
	InsertInjuryPrehab(ctx context.Context, arg InsertInjuryPrehabParams) error
	InsertSkillEdge(ctx context.Context, arg InsertSkillEdgeParams) error
	InsertSkillLevelExercise(ctx context.Context, arg InsertSkillLevelExerciseParams) error
	ListSkillLevelSlugs(ctx context.Context, skillID uuid.UUID) ([]string, error)
	// Removal is soft: rows gone from content are retired, never deleted,
	// because logged set elements reference them.
	RetireExercisesNotIn(ctx context.Context, arg RetireExercisesNotInParams) (int64, error)
	RetireSkillsNotIn(ctx context.Context, arg RetireSkillsNotInParams) (int64, error)
	// Global bands gone from content are soft-deleted; logged assistance keeps
	// pointing at them.
	SoftDeleteGlobalBandsNotIn(ctx context.Context, keys []string) (int64, error)
	UpsertExercise(ctx context.Context, arg UpsertExerciseParams) (uuid.UUID, error)
	UpsertFamily(ctx context.Context, arg UpsertFamilyParams) (uuid.UUID, error)
	UpsertGlobalBand(ctx context.Context, arg UpsertGlobalBandParams) error
	UpsertInjuryRisk(ctx context.Context, arg UpsertInjuryRiskParams) (uuid.UUID, error)
	UpsertSkill(ctx context.Context, arg UpsertSkillParams) (uuid.UUID, error)
	UpsertSkillLevel(ctx context.Context, arg UpsertSkillLevelParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
