// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBlock = `-- name: GetBlock :one
SELECT id, user_id, session_id, order_index, kind, rounds_planned, rounds_done, interval_s, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM session_blocks WHERE id = $1 AND user_id = $2
`

type GetBlockParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBlock(ctx context.Context, arg GetBlockParams) (SessionBlock, error) {
	row := q.db.QueryRow(ctx, getBlock, arg.ID, arg.UserID)
	var i SessionBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.OrderIndex,
		&i.Kind,
		&i.RoundsPlanned,
		&i.RoundsDone,
		&i.IntervalS,
		&i.Notes,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, started_at, ended_at, timezone, local_date, title, notes, perceived_fatigue, bodyweight_kg, status, is_rest_day, template_id, completed_at, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM workout_sessions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.UserID)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Timezone,
		&i.LocalDate,
		&i.Title,
		&i.Notes,
		&i.PerceivedFatigue,
		&i.BodyweightKg,
		&i.Status,
		&i.IsRestDay,
		&i.TemplateID,
		&i.CompletedAt,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, started_at, ended_at, timezone, local_date, title, notes, perceived_fatigue, bodyweight_kg, status, is_rest_day, template_id, completed_at, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM workout_sessions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetSessionForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSessionForUpdate(ctx context.Context, arg GetSessionForUpdateParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, arg.ID, arg.UserID)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Timezone,
		&i.LocalDate,
		&i.Title,
		&i.Notes,
		&i.PerceivedFatigue,
		&i.BodyweightKg,
		&i.Status,
		&i.IsRestDay,
		&i.TemplateID,
		&i.CompletedAt,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const getSetEntry = `-- name: GetSetEntry :one
SELECT id, user_id, session_id, block_id, order_index, round_index, kind, is_planned, rest_after_planned_s, rest_after_actual_s, rpe, rir, completed_at, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM set_entries WHERE id = $1 AND user_id = $2
`

type GetSetEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSetEntry(ctx context.Context, arg GetSetEntryParams) (SetEntry, error) {
	row := q.db.QueryRow(ctx, getSetEntry, arg.ID, arg.UserID)
	var i SetEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.BlockID,
		&i.OrderIndex,
		&i.RoundIndex,
		&i.Kind,
		&i.IsPlanned,
		&i.RestAfterPlannedS,
		&i.RestAfterActualS,
		&i.Rpe,
		&i.Rir,
		&i.CompletedAt,
		&i.Notes,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one


INSERT INTO workout_sessions (
    id, user_id, started_at, timezone, local_date, title, notes, bodyweight_kg,
    is_rest_day, template_id, client_id, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12
)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, started_at, ended_at, timezone, local_date, title, notes, perceived_fatigue, bodyweight_kg, status, is_rest_day, template_id, completed_at, client_id, updated_at, server_updated_at, server_seq, deleted_at
`

type InsertSessionParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	StartedAt    time.Time
	Timezone     string
	LocalDate    pgtype.Date
	Title        string
	Notes        string
	BodyweightKg pgtype.Numeric
	IsRestDay    bool
	TemplateID   *uuid.UUID
	ClientID     *uuid.UUID
	UpdatedAt    time.Time
}

// Sessions -> blocks -> set entries -> set elements (+ assistance).
//
// Every query filters on user_id. Soft-deleted rows are "parked": their
// order_index moves above 999999999, so a tombstone never blocks a live
// sibling from taking its old position (the unique constraint cannot be
// partial and deferrable at the same time).
// ------------------------------------------------------------- sessions
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.StartedAt,
		arg.Timezone,
		arg.LocalDate,
		arg.Title,
		arg.Notes,
		arg.BodyweightKg,
		arg.IsRestDay,
		arg.TemplateID,
		arg.ClientID,
		arg.UpdatedAt,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Timezone,
		&i.LocalDate,
		&i.Title,
		&i.Notes,
		&i.PerceivedFatigue,
		&i.BodyweightKg,
		&i.Status,
		&i.IsRestDay,
		&i.TemplateID,
		&i.CompletedAt,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const lastSetWithExercise = `-- name: LastSetWithExercise :one

SELECT se.id AS set_entry_id, se.session_id, ws.local_date
FROM set_elements el
JOIN set_entries se ON se.id = el.set_entry_id
JOIN workout_sessions ws ON ws.id = se.session_id
WHERE el.user_id = $1 AND el.exercise_id = $2
  AND el.deleted_at IS NULL AND se.deleted_at IS NULL AND ws.deleted_at IS NULL
  AND NOT se.is_planned
ORDER BY COALESCE(se.completed_at, ws.started_at) DESC, ws.started_at DESC, se.order_index DESC
LIMIT 1
`

type LastSetWithExerciseParams struct {
	UserID     uuid.UUID
	ExerciseID uuid.UUID
}

type LastSetWithExerciseRow struct {
	SetEntryID uuid.UUID
	SessionID  uuid.UUID
	LocalDate  pgtype.Date
}

// ------------------------------------------------------------- last set
func (q *Queries) LastSetWithExercise(ctx context.Context, arg LastSetWithExerciseParams) (LastSetWithExerciseRow, error) {
	row := q.db.QueryRow(ctx, lastSetWithExercise, arg.UserID, arg.ExerciseID)
	var i LastSetWithExerciseRow
	err := row.Scan(&i.SetEntryID, &i.SessionID, &i.LocalDate)
	return i, err
}

const listAssistance = `-- name: ListAssistance :many

SELECT a.id, a.user_id, a.set_element_id, a.type, a.band_id, a.band_count, a.anchor, a.estimated_assist_kg, a.note, a.client_id, a.updated_at, a.server_updated_at, a.server_seq, a.deleted_at FROM set_element_assistance a
JOIN set_elements e ON e.id = a.set_element_id
WHERE e.session_id = $1 AND a.user_id = $2 AND a.deleted_at IS NULL
`

type ListAssistanceParams struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
}

// ----------------------------------------------------------- assistance
func (q *Queries) ListAssistance(ctx context.Context, arg ListAssistanceParams) ([]SetElementAssistance, error) {
	rows, err := q.db.Query(ctx, listAssistance, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetElementAssistance{}
	for rows.Next() {
		var i SetElementAssistance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SetElementID,
			&i.Type,
			&i.BandID,
			&i.BandCount,
			&i.Anchor,
			&i.EstimatedAssistKg,
			&i.Note,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many

SELECT id, user_id, session_id, order_index, kind, rounds_planned, rounds_done, interval_s, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM session_blocks
WHERE session_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY order_index
`

type ListBlocksParams struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
}

// --------------------------------------------------------------- blocks
func (q *Queries) ListBlocks(ctx context.Context, arg ListBlocksParams) ([]SessionBlock, error) {
	rows, err := q.db.Query(ctx, listBlocks, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionBlock{}
	for rows.Next() {
		var i SessionBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.OrderIndex,
			&i.Kind,
			&i.RoundsPlanned,
			&i.RoundsDone,
			&i.IntervalS,
			&i.Notes,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listElementsOfSet = `-- name: ListElementsOfSet :many
SELECT id, user_id, session_id, set_entry_id, order_index, exercise_id, measure, reps, hold_seconds, distance_m, tempo, load_kg, is_eccentric_only, is_partial_rom, rom_note, form_quality, failed, assistance_class, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM set_elements
WHERE set_entry_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY order_index
`

type ListElementsOfSetParams struct {
	SetEntryID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) ListElementsOfSet(ctx context.Context, arg ListElementsOfSetParams) ([]SetElement, error) {
	rows, err := q.db.Query(ctx, listElementsOfSet, arg.SetEntryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetElement{}
	for rows.Next() {
		var i SetElement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.SetEntryID,
			&i.OrderIndex,
			&i.ExerciseID,
			&i.Measure,
			&i.Reps,
			&i.HoldSeconds,
			&i.DistanceM,
			&i.Tempo,
			&i.LoadKg,
			&i.IsEccentricOnly,
			&i.IsPartialRom,
			&i.RomNote,
			&i.FormQuality,
			&i.Failed,
			&i.AssistanceClass,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.started_at, s.ended_at, s.timezone, s.local_date, s.title, s.status, s.is_rest_day,
    (SELECT count(*) FROM session_blocks b WHERE b.session_id = s.id AND b.deleted_at IS NULL)::int AS block_count,
    (SELECT count(*) FROM set_entries e WHERE e.session_id = s.id AND e.deleted_at IS NULL)::int AS set_count
FROM workout_sessions s
WHERE s.user_id = $1 AND s.deleted_at IS NULL
  AND ($2::date IS NULL OR s.local_date >= $2)
  AND ($3::date IS NULL OR s.local_date <= $3)
  AND ($4::timestamptz IS NULL
       OR (s.started_at, s.id) < ($4, $5::uuid))
ORDER BY s.started_at DESC, s.id DESC
LIMIT $6
`

type ListSessionsParams struct {
	UserID          uuid.UUID
	FromDate        pgtype.Date
	ToDate          pgtype.Date
	CursorStartedAt *time.Time
	CursorID        *uuid.UUID
	PageLimit       int32
}

type ListSessionsRow struct {
	ID         uuid.UUID
	StartedAt  time.Time
	EndedAt    *time.Time
	Timezone   string
	LocalDate  pgtype.Date
	Title      string
	Status     string
	IsRestDay  bool
	BlockCount int32
	SetCount   int32
}

// Newest first; the cursor is the (started_at, id) of the last row seen.
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.CursorStartedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Timezone,
			&i.LocalDate,
			&i.Title,
			&i.Status,
			&i.IsRestDay,
			&i.BlockCount,
			&i.SetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetElements = `-- name: ListSetElements :many

SELECT id, user_id, session_id, set_entry_id, order_index, exercise_id, measure, reps, hold_seconds, distance_m, tempo, load_kg, is_eccentric_only, is_partial_rom, rom_note, form_quality, failed, assistance_class, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM set_elements
WHERE session_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY set_entry_id, order_index
`

type ListSetElementsParams struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
}

// ------------------------------------------------------------- elements
func (q *Queries) ListSetElements(ctx context.Context, arg ListSetElementsParams) ([]SetElement, error) {
	rows, err := q.db.Query(ctx, listSetElements, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetElement{}
	for rows.Next() {
		var i SetElement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.SetEntryID,
			&i.OrderIndex,
			&i.ExerciseID,
			&i.Measure,
			&i.Reps,
			&i.HoldSeconds,
			&i.DistanceM,
			&i.Tempo,
			&i.LoadKg,
			&i.IsEccentricOnly,
			&i.IsPartialRom,
			&i.RomNote,
			&i.FormQuality,
			&i.Failed,
			&i.AssistanceClass,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetEntries = `-- name: ListSetEntries :many

SELECT id, user_id, session_id, block_id, order_index, round_index, kind, is_planned, rest_after_planned_s, rest_after_actual_s, rpe, rir, completed_at, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM set_entries
WHERE session_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY block_id, order_index
`

type ListSetEntriesParams struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
}

// ----------------------------------------------------------------- sets
func (q *Queries) ListSetEntries(ctx context.Context, arg ListSetEntriesParams) ([]SetEntry, error) {
	rows, err := q.db.Query(ctx, listSetEntries, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetEntry{}
	for rows.Next() {
		var i SetEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.BlockID,
			&i.OrderIndex,
			&i.RoundIndex,
			&i.Kind,
			&i.IsPlanned,
			&i.RestAfterPlannedS,
			&i.RestAfterActualS,
			&i.Rpe,
			&i.Rir,
			&i.CompletedAt,
			&i.Notes,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionCompleted = `-- name: MarkSessionCompleted :one
UPDATE workout_sessions SET
    status = 'completed', completed_at = $1, ended_at = $2,
    perceived_fatigue = $3, bodyweight_kg = $4,
    client_id = $5, updated_at = $6
WHERE id = $7 AND user_id = $8 AND deleted_at IS NULL AND status = 'draft'
RETURNING id, user_id, started_at, ended_at, timezone, local_date, title, notes, perceived_fatigue, bodyweight_kg, status, is_rest_day, template_id, completed_at, client_id, updated_at, server_updated_at, server_seq, deleted_at
`

type MarkSessionCompletedParams struct {
	CompletedAt      *time.Time
	EndedAt          *time.Time
	PerceivedFatigue *int16
	BodyweightKg     pgtype.Numeric
	ClientID         *uuid.UUID
	UpdatedAt        time.Time
	ID               uuid.UUID
	UserID           uuid.UUID
}

func (q *Queries) MarkSessionCompleted(ctx context.Context, arg MarkSessionCompletedParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, markSessionCompleted,
		arg.CompletedAt,
		arg.EndedAt,
		arg.PerceivedFatigue,
		arg.BodyweightKg,
		arg.ClientID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Timezone,
		&i.LocalDate,
		&i.Title,
		&i.Notes,
		&i.PerceivedFatigue,
		&i.BodyweightKg,
		&i.Status,
		&i.IsRestDay,
		&i.TemplateID,
		&i.CompletedAt,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const setBlockOrder = `-- name: SetBlockOrder :exec
UPDATE session_blocks b
SET order_index = o.ord - 1, client_id = $1, updated_at = $2
FROM unnest($5::uuid[]) WITH ORDINALITY AS o(id, ord)
WHERE b.id = o.id AND b.user_id = $3 AND b.session_id = $4 AND b.deleted_at IS NULL
`

type SetBlockOrderParams struct {
	ClientID  *uuid.UUID
	UpdatedAt time.Time
	UserID    uuid.UUID
	SessionID uuid.UUID
	Ids       []uuid.UUID
}

func (q *Queries) SetBlockOrder(ctx context.Context, arg SetBlockOrderParams) error {
	_, err := q.db.Exec(ctx, setBlockOrder,
		arg.ClientID,
		arg.UpdatedAt,
		arg.UserID,
		arg.SessionID,
		arg.Ids,
	)
	return err
}

const setSetOrder = `-- name: SetSetOrder :exec
UPDATE set_entries s
SET order_index = o.ord - 1, client_id = $1, updated_at = $2
FROM unnest($5::uuid[]) WITH ORDINALITY AS o(id, ord)
WHERE s.id = o.id AND s.user_id = $3 AND s.block_id = $4 AND s.deleted_at IS NULL
`

type SetSetOrderParams struct {
	ClientID  *uuid.UUID
	UpdatedAt time.Time
	UserID    uuid.UUID
	BlockID   uuid.UUID
	Ids       []uuid.UUID
}

func (q *Queries) SetSetOrder(ctx context.Context, arg SetSetOrderParams) error {
	_, err := q.db.Exec(ctx, setSetOrder,
		arg.ClientID,
		arg.UpdatedAt,
		arg.UserID,
		arg.BlockID,
		arg.Ids,
	)
	return err
}

const softDeleteBlocksOfSession = `-- name: SoftDeleteBlocksOfSession :exec
WITH base AS (
    SELECT GREATEST(COALESCE(MAX(sb.order_index), 0), 999999999) AS m
    FROM session_blocks sb WHERE sb.session_id = $3
), doomed AS (
    SELECT d.id, row_number() OVER (ORDER BY d.order_index) AS n
    FROM session_blocks d
    WHERE d.session_id = $3 AND d.user_id = $4 AND d.deleted_at IS NULL
      AND ($5::uuid IS NULL OR d.id = $5)
)
UPDATE session_blocks b
SET deleted_at = now(), order_index = base.m + doomed.n, client_id = $1, updated_at = $2
FROM doomed, base
WHERE b.id = doomed.id
`

type SoftDeleteBlocksOfSessionParams struct {
	ClientID  *uuid.UUID
	UpdatedAt time.Time
	SessionID uuid.UUID
	UserID    uuid.UUID
	OnlyID    *uuid.UUID
}

func (q *Queries) SoftDeleteBlocksOfSession(ctx context.Context, arg SoftDeleteBlocksOfSessionParams) error {
	_, err := q.db.Exec(ctx, softDeleteBlocksOfSession,
		arg.ClientID,
		arg.UpdatedAt,
		arg.SessionID,
		arg.UserID,
		arg.OnlyID,
	)
	return err
}

const softDeleteOtherAssistance = `-- name: SoftDeleteOtherAssistance :exec
UPDATE set_element_assistance
SET deleted_at = now(), client_id = $1, updated_at = $2
WHERE set_element_id = $3 AND user_id = $4 AND deleted_at IS NULL
  AND ($5::uuid IS NULL OR id <> $5)
`

type SoftDeleteOtherAssistanceParams struct {
	ClientID     *uuid.UUID
	UpdatedAt    time.Time
	SetElementID uuid.UUID
	UserID       uuid.UUID
	KeepID       *uuid.UUID
}

// An element has at most one live assistance row: the one being kept, if any.
func (q *Queries) SoftDeleteOtherAssistance(ctx context.Context, arg SoftDeleteOtherAssistanceParams) error {
	_, err := q.db.Exec(ctx, softDeleteOtherAssistance,
		arg.ClientID,
		arg.UpdatedAt,
		arg.SetElementID,
		arg.UserID,
		arg.KeepID,
	)
	return err
}

const softDeleteSession = `-- name: SoftDeleteSession :execrows
UPDATE workout_sessions SET deleted_at = now(), client_id = $1, updated_at = $2
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL
`

type SoftDeleteSessionParams struct {
	ClientID  *uuid.UUID
	UpdatedAt time.Time
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) SoftDeleteSession(ctx context.Context, arg SoftDeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSession,
		arg.ClientID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteSetElements = `-- name: SoftDeleteSetElements :exec
WITH doomed AS (
    SELECT d.id, d.set_entry_id, row_number() OVER (PARTITION BY d.set_entry_id ORDER BY d.order_index) AS n
    FROM set_elements d
    WHERE d.session_id = $3 AND d.user_id = $4 AND d.deleted_at IS NULL
      AND ($5::uuid IS NULL OR d.set_entry_id = $5)
      AND ($6::uuid IS NULL
           OR d.set_entry_id IN (SELECT se.id FROM set_entries se WHERE se.block_id = $6))
      AND NOT (d.id = ANY($7::uuid[]))
), base AS (
    SELECT x.set_entry_id, GREATEST(COALESCE(MAX(x.order_index), 0), 999999999) AS m
    FROM set_elements x WHERE x.set_entry_id IN (SELECT set_entry_id FROM doomed)
    GROUP BY x.set_entry_id
), gone_assistance AS (
    UPDATE set_element_assistance a
    SET deleted_at = now(), client_id = $1, updated_at = $2
    WHERE a.set_element_id IN (SELECT id FROM doomed) AND a.deleted_at IS NULL
)
UPDATE set_elements e
SET deleted_at = now(), order_index = base.m + doomed.n, client_id = $1, updated_at = $2
FROM doomed JOIN base ON base.set_entry_id = doomed.set_entry_id
WHERE e.id = doomed.id
`

type SoftDeleteSetElementsParams struct {
	ClientID   *uuid.UUID
	UpdatedAt  time.Time
	SessionID  uuid.UUID
	UserID     uuid.UUID
	SetEntryID *uuid.UUID
	BlockID    *uuid.UUID
	Keep       []uuid.UUID
}

// Tombstones the live elements of sets (a whole session, one set, or those
// of one set not in keep) along with their assistance rows.
func (q *Queries) SoftDeleteSetElements(ctx context.Context, arg SoftDeleteSetElementsParams) error {
	_, err := q.db.Exec(ctx, softDeleteSetElements,
		arg.ClientID,
		arg.UpdatedAt,
		arg.SessionID,
		arg.UserID,
		arg.SetEntryID,
		arg.BlockID,
		arg.Keep,
	)
	return err
}

const softDeleteSetEntries = `-- name: SoftDeleteSetEntries :exec
WITH doomed AS (
    SELECT d.id, d.block_id, row_number() OVER (PARTITION BY d.block_id ORDER BY d.order_index) AS n
    FROM set_entries d
    WHERE d.session_id = $3 AND d.user_id = $4 AND d.deleted_at IS NULL
      AND ($5::uuid IS NULL OR d.block_id = $5)
      AND ($6::uuid IS NULL OR d.id = $6)
), base AS (
    SELECT x.block_id, GREATEST(COALESCE(MAX(x.order_index), 0), 999999999) AS m
    FROM set_entries x WHERE x.block_id IN (SELECT block_id FROM doomed)
    GROUP BY x.block_id
)
UPDATE set_entries s
SET deleted_at = now(), order_index = base.m + doomed.n, client_id = $1, updated_at = $2
FROM doomed JOIN base ON base.block_id = doomed.block_id
WHERE s.id = doomed.id
`

type SoftDeleteSetEntriesParams struct {
	ClientID  *uuid.UUID
	UpdatedAt time.Time
	SessionID uuid.UUID
	UserID    uuid.UUID
	BlockID   *uuid.UUID
	OnlyID    *uuid.UUID
}

// Parks and tombstones live sets of a block, or of the whole session, or one set.
func (q *Queries) SoftDeleteSetEntries(ctx context.Context, arg SoftDeleteSetEntriesParams) error {
	_, err := q.db.Exec(ctx, softDeleteSetEntries,
		arg.ClientID,
		arg.UpdatedAt,
		arg.SessionID,
		arg.UserID,
		arg.BlockID,
		arg.OnlyID,
	)
	return err
}

const templateBelongsToUser = `-- name: TemplateBelongsToUser :one
SELECT EXISTS (
    SELECT 1 FROM workout_templates
    WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
)
`

type TemplateBelongsToUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) TemplateBelongsToUser(ctx context.Context, arg TemplateBelongsToUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, templateBelongsToUser, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE workout_sessions SET
    started_at = $1, ended_at = $2, timezone = $3,
    local_date = $4, title = $5, notes = $6,
    perceived_fatigue = $7, bodyweight_kg = $8,
    is_rest_day = $9, status = $10,
    client_id = $11, updated_at = $12
WHERE id = $13 AND user_id = $14 AND deleted_at IS NULL
RETURNING id, user_id, started_at, ended_at, timezone, local_date, title, notes, perceived_fatigue, bodyweight_kg, status, is_rest_day, template_id, completed_at, client_id, updated_at, server_updated_at, server_seq, deleted_at
`

type UpdateSessionParams struct {
	StartedAt        time.Time
	EndedAt          *time.Time
	Timezone         string
	LocalDate        pgtype.Date
	Title            string
	Notes            string
	PerceivedFatigue *int16
	BodyweightKg     pgtype.Numeric
	IsRestDay        bool
	Status           string
	ClientID         *uuid.UUID
	UpdatedAt        time.Time
	ID               uuid.UUID
	UserID           uuid.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.StartedAt,
		arg.EndedAt,
		arg.Timezone,
		arg.LocalDate,
		arg.Title,
		arg.Notes,
		arg.PerceivedFatigue,
		arg.BodyweightKg,
		arg.IsRestDay,
		arg.Status,
		arg.ClientID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Timezone,
		&i.LocalDate,
		&i.Title,
		&i.Notes,
		&i.PerceivedFatigue,
		&i.BodyweightKg,
		&i.Status,
		&i.IsRestDay,
		&i.TemplateID,
		&i.CompletedAt,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const upsertAssistance = `-- name: UpsertAssistance :one
INSERT INTO set_element_assistance AS a (
    id, user_id, set_element_id, type, band_id, band_count, anchor,
    estimated_assist_kg, note, client_id, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, band_id = EXCLUDED.band_id, band_count = EXCLUDED.band_count,
    anchor = EXCLUDED.anchor, estimated_assist_kg = EXCLUDED.estimated_assist_kg,
    note = EXCLUDED.note, client_id = EXCLUDED.client_id, updated_at = EXCLUDED.updated_at
WHERE a.user_id = EXCLUDED.user_id AND a.set_element_id = EXCLUDED.set_element_id AND a.deleted_at IS NULL
RETURNING id
`

type UpsertAssistanceParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	SetElementID      uuid.UUID
	Type              string
	BandID            *uuid.UUID
	BandCount         int16
	Anchor            *string
	EstimatedAssistKg pgtype.Numeric
	Note              string
	ClientID          *uuid.UUID
	UpdatedAt         time.Time
}

func (q *Queries) UpsertAssistance(ctx context.Context, arg UpsertAssistanceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAssistance,
		arg.ID,
		arg.UserID,
		arg.SetElementID,
		arg.Type,
		arg.BandID,
		arg.BandCount,
		arg.Anchor,
		arg.EstimatedAssistKg,
		arg.Note,
		arg.ClientID,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertBlock = `-- name: UpsertBlock :one
INSERT INTO session_blocks AS b (
    id, user_id, session_id, order_index, kind, rounds_planned, rounds_done,
    interval_s, notes, client_id, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
    order_index = EXCLUDED.order_index, kind = EXCLUDED.kind,
    rounds_planned = EXCLUDED.rounds_planned, rounds_done = EXCLUDED.rounds_done,
    interval_s = EXCLUDED.interval_s, notes = EXCLUDED.notes,
    client_id = EXCLUDED.client_id, updated_at = EXCLUDED.updated_at
WHERE b.user_id = EXCLUDED.user_id AND b.session_id = EXCLUDED.session_id AND b.deleted_at IS NULL
RETURNING id, user_id, session_id, order_index, kind, rounds_planned, rounds_done, interval_s, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at, (xmax = 0) AS inserted
`

type UpsertBlockParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SessionID     uuid.UUID
	OrderIndex    int32
	Kind          string
	RoundsPlanned *int16
	RoundsDone    *int16
	IntervalS     *int32
	Notes         string
	ClientID      *uuid.UUID
	UpdatedAt     time.Time
}

type UpsertBlockRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	SessionID       uuid.UUID
	OrderIndex      int32
	Kind            string
	RoundsPlanned   *int16
	RoundsDone      *int16
	IntervalS       *int32
	Notes           string
	ClientID        *uuid.UUID
	UpdatedAt       time.Time
	ServerUpdatedAt time.Time
	ServerSeq       int64
	DeletedAt       *time.Time
	Inserted        bool
}

// Inserts, or replaces a live block of the same session. Returns no row when
// the id belongs to another session or user, or is a tombstone.
func (q *Queries) UpsertBlock(ctx context.Context, arg UpsertBlockParams) (UpsertBlockRow, error) {
	row := q.db.QueryRow(ctx, upsertBlock,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.OrderIndex,
		arg.Kind,
		arg.RoundsPlanned,
		arg.RoundsDone,
		arg.IntervalS,
		arg.Notes,
		arg.ClientID,
		arg.UpdatedAt,
	)
	var i UpsertBlockRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.OrderIndex,
		&i.Kind,
		&i.RoundsPlanned,
		&i.RoundsDone,
		&i.IntervalS,
		&i.Notes,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
		&i.Inserted,
	)
	return i, err
}

const upsertSetElement = `-- name: UpsertSetElement :one
INSERT INTO set_elements AS e (
    id, user_id, session_id, set_entry_id, order_index, exercise_id, measure,
    reps, hold_seconds, distance_m, tempo, load_kg, is_eccentric_only,
    is_partial_rom, rom_note, form_quality, failed, assistance_class,
    client_id, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20
)
ON CONFLICT (id) DO UPDATE SET
    order_index = EXCLUDED.order_index, exercise_id = EXCLUDED.exercise_id,
    measure = EXCLUDED.measure, reps = EXCLUDED.reps, hold_seconds = EXCLUDED.hold_seconds,
    distance_m = EXCLUDED.distance_m, tempo = EXCLUDED.tempo, load_kg = EXCLUDED.load_kg,
    is_eccentric_only = EXCLUDED.is_eccentric_only, is_partial_rom = EXCLUDED.is_partial_rom,
    rom_note = EXCLUDED.rom_note, form_quality = EXCLUDED.form_quality, failed = EXCLUDED.failed,
    assistance_class = EXCLUDED.assistance_class,
    client_id = EXCLUDED.client_id, updated_at = EXCLUDED.updated_at
WHERE e.user_id = EXCLUDED.user_id AND e.set_entry_id = EXCLUDED.set_entry_id AND e.deleted_at IS NULL
RETURNING id
`

type UpsertSetElementParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	SessionID       uuid.UUID
	SetEntryID      uuid.UUID
	OrderIndex      int32
	ExerciseID      uuid.UUID
	Measure         string
	Reps            *int32
	HoldSeconds     pgtype.Numeric
	DistanceM       pgtype.Numeric
	Tempo           *string
	LoadKg          pgtype.Numeric
	IsEccentricOnly bool
	IsPartialRom    bool
	RomNote         *string
	FormQuality     *int16
	Failed          bool
	AssistanceClass string
	ClientID        *uuid.UUID
	UpdatedAt       time.Time
}

func (q *Queries) UpsertSetElement(ctx context.Context, arg UpsertSetElementParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSetElement,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.SetEntryID,
		arg.OrderIndex,
		arg.ExerciseID,
		arg.Measure,
		arg.Reps,
		arg.HoldSeconds,
		arg.DistanceM,
		arg.Tempo,
		arg.LoadKg,
		arg.IsEccentricOnly,
		arg.IsPartialRom,
		arg.RomNote,
		arg.FormQuality,
		arg.Failed,
		arg.AssistanceClass,
		arg.ClientID,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSetEntry = `-- name: UpsertSetEntry :one
INSERT INTO set_entries AS s (
    id, user_id, session_id, block_id, order_index, round_index, kind, is_planned,
    rest_after_planned_s, rest_after_actual_s, rpe, rir, completed_at, notes,
    client_id, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16
)
ON CONFLICT (id) DO UPDATE SET
    block_id = EXCLUDED.block_id, order_index = EXCLUDED.order_index,
    round_index = EXCLUDED.round_index, kind = EXCLUDED.kind, is_planned = EXCLUDED.is_planned,
    rest_after_planned_s = EXCLUDED.rest_after_planned_s,
    rest_after_actual_s = EXCLUDED.rest_after_actual_s,
    rpe = EXCLUDED.rpe, rir = EXCLUDED.rir, completed_at = EXCLUDED.completed_at,
    notes = EXCLUDED.notes, client_id = EXCLUDED.client_id, updated_at = EXCLUDED.updated_at
WHERE s.user_id = EXCLUDED.user_id AND s.session_id = EXCLUDED.session_id AND s.deleted_at IS NULL
RETURNING id, user_id, session_id, block_id, order_index, round_index, kind, is_planned, rest_after_planned_s, rest_after_actual_s, rpe, rir, completed_at, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at, (xmax = 0) AS inserted
`

type UpsertSetEntryParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	SessionID         uuid.UUID
	BlockID           uuid.UUID
	OrderIndex        int32
	RoundIndex        *int16
	Kind              string
	IsPlanned         bool
	RestAfterPlannedS *int32
	RestAfterActualS  *int32
	Rpe               pgtype.Numeric
	Rir               *int16
	CompletedAt       *time.Time
	Notes             string
	ClientID          *uuid.UUID
	UpdatedAt         time.Time
}

type UpsertSetEntryRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	SessionID         uuid.UUID
	BlockID           uuid.UUID
	OrderIndex        int32
	RoundIndex        *int16
	Kind              string
	IsPlanned         bool
	RestAfterPlannedS *int32
	RestAfterActualS  *int32
	Rpe               pgtype.Numeric
	Rir               *int16
	CompletedAt       *time.Time
	Notes             string
	ClientID          *uuid.UUID
	UpdatedAt         time.Time
	ServerUpdatedAt   time.Time
	ServerSeq         int64
	DeletedAt         *time.Time
	Inserted          bool
}

func (q *Queries) UpsertSetEntry(ctx context.Context, arg UpsertSetEntryParams) (UpsertSetEntryRow, error) {
	row := q.db.QueryRow(ctx, upsertSetEntry,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.BlockID,
		arg.OrderIndex,
		arg.RoundIndex,
		arg.Kind,
		arg.IsPlanned,
		arg.RestAfterPlannedS,
		arg.RestAfterActualS,
		arg.Rpe,
		arg.Rir,
		arg.CompletedAt,
		arg.Notes,
		arg.ClientID,
		arg.UpdatedAt,
	)
	var i UpsertSetEntryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.BlockID,
		&i.OrderIndex,
		&i.RoundIndex,
		&i.Kind,
		&i.IsPlanned,
		&i.RestAfterPlannedS,
		&i.RestAfterActualS,
		&i.Rpe,
		&i.Rir,
		&i.CompletedAt,
		&i.Notes,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
		&i.Inserted,
	)
	return i, err
}
