// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sync.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ackSyncCursor = `-- name: AckSyncCursor :exec
UPDATE devices SET last_sync_seq = GREATEST(last_sync_seq, $1::bigint), last_seen_at = now()
WHERE id = $2 AND user_id = $3
`

type AckSyncCursorParams struct {
	Cursor   int64
	DeviceID uuid.UUID
	UserID   uuid.UUID
}

// The device has everything up to this cursor.
func (q *Queries) AckSyncCursor(ctx context.Context, arg AckSyncCursorParams) error {
	_, err := q.db.Exec(ctx, ackSyncCursor, arg.Cursor, arg.DeviceID, arg.UserID)
	return err
}

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one

INSERT INTO idempotency_keys AS k (user_id, key, request_fingerprint)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET
    request_fingerprint = EXCLUDED.request_fingerprint, state = 'in_progress',
    response_status = NULL, response_body = NULL, created_at = now(), completed_at = NULL,
    expires_at = now() + interval '24 hours'
WHERE k.expires_at < now()
   OR (k.state = 'in_progress' AND k.created_at < now() - interval '5 minutes'
       AND k.request_fingerprint = EXCLUDED.request_fingerprint)
RETURNING k.key
`

type ClaimIdempotencyKeyParams struct {
	UserID             uuid.UUID
	Key                string
	RequestFingerprint []byte
}

// ----------------------------------------------------------- idempotency
// Claims a key: a new key, an expired one, or one whose earlier attempt
// stalled (in progress for five minutes, same request) is taken. Returns no
// row when the key is live and held.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey, arg.UserID, arg.Key, arg.RequestFingerprint)
	var key string
	err := row.Scan(&key)
	return key, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys SET state = 'completed', response_status = $1,
    response_body = $2, completed_at = now()
WHERE user_id = $3 AND key = $4
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus *int32
	ResponseBody   []byte
	UserID         uuid.UUID
	Key            string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.UserID,
		arg.Key,
	)
	return err
}

const getBodyweight = `-- name: GetBodyweight :one
SELECT id, user_id, measured_at, local_date, bodyweight_kg, note, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM user_bodyweight_log WHERE id = $1 AND user_id = $2
`

type GetBodyweightParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetBodyweight(ctx context.Context, arg GetBodyweightParams) (UserBodyweightLog, error) {
	row := q.db.QueryRow(ctx, getBodyweight, arg.ID, arg.UserID)
	var i UserBodyweightLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MeasuredAt,
		&i.LocalDate,
		&i.BodyweightKg,
		&i.Note,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, key, request_fingerprint, state, response_status, response_body, created_at, completed_at, expires_at FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.RequestFingerprint,
		&i.State,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const purgeExpiredIdempotencyKeys = `-- name: PurgeExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) PurgeExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE user_id = $1 AND key = $2 AND state = 'in_progress'
`

type ReleaseIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    string
}

// A failed attempt gives the key back, so the client can retry with it.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.UserID, arg.Key)
	return err
}

const softDeleteBodyweight = `-- name: SoftDeleteBodyweight :execrows
UPDATE user_bodyweight_log SET deleted_at = now(), client_id = $1, updated_at = $2
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL
`

type SoftDeleteBodyweightParams struct {
	ClientID  *uuid.UUID
	UpdatedAt time.Time
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) SoftDeleteBodyweight(ctx context.Context, arg SoftDeleteBodyweightParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteBodyweight,
		arg.ClientID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const syncAssistanceOfSets = `-- name: SyncAssistanceOfSets :many
SELECT a.id, a.user_id, a.set_element_id, a.type, a.band_id, a.band_count, a.anchor, a.estimated_assist_kg, a.note, a.client_id, a.updated_at, a.server_updated_at, a.server_seq, a.deleted_at FROM set_element_assistance a
JOIN set_elements el ON el.id = a.set_element_id
WHERE a.user_id = $1 AND el.set_entry_id = ANY($2::uuid[])
  AND a.deleted_at IS NULL AND el.deleted_at IS NULL
`

type SyncAssistanceOfSetsParams struct {
	UserID uuid.UUID
	SetIds []uuid.UUID
}

func (q *Queries) SyncAssistanceOfSets(ctx context.Context, arg SyncAssistanceOfSetsParams) ([]SetElementAssistance, error) {
	rows, err := q.db.Query(ctx, syncAssistanceOfSets, arg.UserID, arg.SetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetElementAssistance{}
	for rows.Next() {
		var i SetElementAssistance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SetElementID,
			&i.Type,
			&i.BandID,
			&i.BandCount,
			&i.Anchor,
			&i.EstimatedAssistKg,
			&i.Note,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncBlocks = `-- name: SyncBlocks :many
SELECT id, user_id, session_id, order_index, kind, rounds_planned, rounds_done, interval_s, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM session_blocks WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type SyncBlocksParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) SyncBlocks(ctx context.Context, arg SyncBlocksParams) ([]SessionBlock, error) {
	rows, err := q.db.Query(ctx, syncBlocks, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionBlock{}
	for rows.Next() {
		var i SessionBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.OrderIndex,
			&i.Kind,
			&i.RoundsPlanned,
			&i.RoundsDone,
			&i.IntervalS,
			&i.Notes,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncBodyweight = `-- name: SyncBodyweight :many
SELECT id, user_id, measured_at, local_date, bodyweight_kg, note, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM user_bodyweight_log WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type SyncBodyweightParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) SyncBodyweight(ctx context.Context, arg SyncBodyweightParams) ([]UserBodyweightLog, error) {
	rows, err := q.db.Query(ctx, syncBodyweight, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBodyweightLog{}
	for rows.Next() {
		var i UserBodyweightLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MeasuredAt,
			&i.LocalDate,
			&i.BodyweightKg,
			&i.Note,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncChanges = `-- name: SyncChanges :many


WITH set_units AS (
    SELECT u.set_entry_id AS id, max(u.seq)::bigint AS seq
    FROM (
        SELECT se.id AS set_entry_id, se.server_seq AS seq
        FROM set_entries se WHERE se.user_id = $1 AND se.server_seq > $2
        UNION ALL
        SELECT el.set_entry_id, el.server_seq
        FROM set_elements el WHERE el.user_id = $1 AND el.server_seq > $2
        UNION ALL
        SELECT el.set_entry_id, a.server_seq
        FROM set_element_assistance a JOIN set_elements el ON el.id = a.set_element_id
        WHERE a.user_id = $1 AND a.server_seq > $2
    ) u
    GROUP BY u.set_entry_id
)
SELECT c.entity::text AS entity, c.id::uuid AS id, c.seq::bigint AS seq
FROM (
    SELECT 'session' AS entity, s.id, s.server_seq AS seq
    FROM workout_sessions s WHERE s.user_id = $1 AND s.server_seq > $2
    UNION ALL
    SELECT 'block', b.id, b.server_seq
    FROM session_blocks b WHERE b.user_id = $1 AND b.server_seq > $2
    UNION ALL
    SELECT 'set', su.id, su.seq FROM set_units su
    UNION ALL
    SELECT 'bodyweight', w.id, w.server_seq
    FROM user_bodyweight_log w WHERE w.user_id = $1 AND w.server_seq > $2
) c
ORDER BY c.seq
LIMIT $3
`

type SyncChangesParams struct {
	UserID    uuid.UUID
	Cursor    int64
	PageLimit int32
}

type SyncChangesRow struct {
	Entity string
	ID     uuid.UUID
	Seq    int64
}

// Delta sync, offline push bookkeeping and the bodyweight log.
//
// server_seq is a per-user total order over writes (next_sync_seq takes it
// from the user's row, so concurrent writers of one user serialise). The feed
// pages over it exactly: every unit appears at its latest change.
// ------------------------------------------------------------------ pull
// A set is one unit with its elements and their assistance: it changes when
// any of them does, and appears at the latest of those changes.
func (q *Queries) SyncChanges(ctx context.Context, arg SyncChangesParams) ([]SyncChangesRow, error) {
	rows, err := q.db.Query(ctx, syncChanges, arg.UserID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncChangesRow{}
	for rows.Next() {
		var i SyncChangesRow
		if err := rows.Scan(&i.Entity, &i.ID, &i.Seq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncElementMediaOfSets = `-- name: SyncElementMediaOfSets :many
SELECT sem.set_element_id, sem.media_id
FROM set_element_media sem
JOIN set_elements el ON el.id = sem.set_element_id
JOIN media_assets m ON m.id = sem.media_id
WHERE sem.user_id = $1 AND el.set_entry_id = ANY($2::uuid[]) AND m.deleted_at IS NULL
ORDER BY sem.set_element_id, sem.order_index, sem.media_id
`

type SyncElementMediaOfSetsParams struct {
	UserID uuid.UUID
	SetIds []uuid.UUID
}

type SyncElementMediaOfSetsRow struct {
	SetElementID uuid.UUID
	MediaID      uuid.UUID
}

func (q *Queries) SyncElementMediaOfSets(ctx context.Context, arg SyncElementMediaOfSetsParams) ([]SyncElementMediaOfSetsRow, error) {
	rows, err := q.db.Query(ctx, syncElementMediaOfSets, arg.UserID, arg.SetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncElementMediaOfSetsRow{}
	for rows.Next() {
		var i SyncElementMediaOfSetsRow
		if err := rows.Scan(&i.SetElementID, &i.MediaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncElementsOfSets = `-- name: SyncElementsOfSets :many
SELECT id, user_id, session_id, set_entry_id, order_index, exercise_id, measure, reps, hold_seconds, distance_m, tempo, load_kg, is_eccentric_only, is_partial_rom, rom_note, form_quality, failed, assistance_class, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM set_elements
WHERE user_id = $1 AND set_entry_id = ANY($2::uuid[]) AND deleted_at IS NULL
ORDER BY set_entry_id, order_index
`

type SyncElementsOfSetsParams struct {
	UserID uuid.UUID
	SetIds []uuid.UUID
}

func (q *Queries) SyncElementsOfSets(ctx context.Context, arg SyncElementsOfSetsParams) ([]SetElement, error) {
	rows, err := q.db.Query(ctx, syncElementsOfSets, arg.UserID, arg.SetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetElement{}
	for rows.Next() {
		var i SetElement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.SetEntryID,
			&i.OrderIndex,
			&i.ExerciseID,
			&i.Measure,
			&i.Reps,
			&i.HoldSeconds,
			&i.DistanceM,
			&i.Tempo,
			&i.LoadKg,
			&i.IsEccentricOnly,
			&i.IsPartialRom,
			&i.RomNote,
			&i.FormQuality,
			&i.Failed,
			&i.AssistanceClass,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncSessions = `-- name: SyncSessions :many
SELECT id, user_id, started_at, ended_at, timezone, local_date, title, notes, perceived_fatigue, bodyweight_kg, status, is_rest_day, template_id, completed_at, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM workout_sessions WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type SyncSessionsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) SyncSessions(ctx context.Context, arg SyncSessionsParams) ([]WorkoutSession, error) {
	rows, err := q.db.Query(ctx, syncSessions, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSession{}
	for rows.Next() {
		var i WorkoutSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Timezone,
			&i.LocalDate,
			&i.Title,
			&i.Notes,
			&i.PerceivedFatigue,
			&i.BodyweightKg,
			&i.Status,
			&i.IsRestDay,
			&i.TemplateID,
			&i.CompletedAt,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncSetEntries = `-- name: SyncSetEntries :many
SELECT id, user_id, session_id, block_id, order_index, round_index, kind, is_planned, rest_after_planned_s, rest_after_actual_s, rpe, rir, completed_at, notes, client_id, updated_at, server_updated_at, server_seq, deleted_at FROM set_entries WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type SyncSetEntriesParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) SyncSetEntries(ctx context.Context, arg SyncSetEntriesParams) ([]SetEntry, error) {
	rows, err := q.db.Query(ctx, syncSetEntries, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetEntry{}
	for rows.Next() {
		var i SetEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.BlockID,
			&i.OrderIndex,
			&i.RoundIndex,
			&i.Kind,
			&i.IsPlanned,
			&i.RestAfterPlannedS,
			&i.RestAfterActualS,
			&i.Rpe,
			&i.Rir,
			&i.CompletedAt,
			&i.Notes,
			&i.ClientID,
			&i.UpdatedAt,
			&i.ServerUpdatedAt,
			&i.ServerSeq,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncSetSeqs = `-- name: SyncSetSeqs :many
SELECT se.id,
       GREATEST(se.server_seq,
                COALESCE((SELECT max(el.server_seq) FROM set_elements el WHERE el.set_entry_id = se.id), 0),
                COALESCE((SELECT max(a.server_seq) FROM set_element_assistance a
                          JOIN set_elements el ON el.id = a.set_element_id
                          WHERE el.set_entry_id = se.id), 0))::bigint AS seq
FROM set_entries se
WHERE se.user_id = $1 AND se.id = ANY($2::uuid[])
`

type SyncSetSeqsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

type SyncSetSeqsRow struct {
	ID  uuid.UUID
	Seq int64
}

// The latest change to each set unit, for sets pulled in as a whole.
func (q *Queries) SyncSetSeqs(ctx context.Context, arg SyncSetSeqsParams) ([]SyncSetSeqsRow, error) {
	rows, err := q.db.Query(ctx, syncSetSeqs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncSetSeqsRow{}
	for rows.Next() {
		var i SyncSetSeqsRow
		if err := rows.Scan(&i.ID, &i.Seq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBodyweight = `-- name: UpsertBodyweight :one

INSERT INTO user_bodyweight_log AS w (
    id, user_id, measured_at, local_date, bodyweight_kg, note, client_id, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    measured_at = EXCLUDED.measured_at, local_date = EXCLUDED.local_date,
    bodyweight_kg = EXCLUDED.bodyweight_kg, note = EXCLUDED.note,
    client_id = EXCLUDED.client_id, updated_at = EXCLUDED.updated_at
WHERE w.user_id = EXCLUDED.user_id AND w.deleted_at IS NULL
RETURNING id, user_id, measured_at, local_date, bodyweight_kg, note, client_id, updated_at, server_updated_at, server_seq, deleted_at
`

type UpsertBodyweightParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	MeasuredAt   time.Time
	LocalDate    pgtype.Date
	BodyweightKg pgtype.Numeric
	Note         string
	ClientID     *uuid.UUID
	UpdatedAt    time.Time
}

// ------------------------------------------------------------ bodyweight
// Inserts, or replaces a live entry of the same user. No row for a tombstone
// or another user's id.
func (q *Queries) UpsertBodyweight(ctx context.Context, arg UpsertBodyweightParams) (UserBodyweightLog, error) {
	row := q.db.QueryRow(ctx, upsertBodyweight,
		arg.ID,
		arg.UserID,
		arg.MeasuredAt,
		arg.LocalDate,
		arg.BodyweightKg,
		arg.Note,
		arg.ClientID,
		arg.UpdatedAt,
	)
	var i UserBodyweightLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MeasuredAt,
		&i.LocalDate,
		&i.BodyweightKg,
		&i.Note,
		&i.ClientID,
		&i.UpdatedAt,
		&i.ServerUpdatedAt,
		&i.ServerSeq,
		&i.DeletedAt,
	)
	return i, err
}
